import React, { useEffect, useState } from 'react';
import { accountantPortalService, type AccountantSaleDetails } from '../../services/accountantPortalService';
import { AccountantFiscalFileActions } from './AccountantFiscalFileActions';
import { getPaymentLabel } from '../../utils/salePresentation';

const money = (value: number | null) => value == null ? 'Não informado' : (value / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const statusLabel: Record<string, string> = { authorized:'Autorizada', cancelled:'Cancelada', rejected:'Rejeitada', denied:'Denegada', reserved:'Número reservado', prepared:'Preparada', sending:'Em envio', uncertain:'Aguardando confirmação', paid:'Pago', pending:'Pendente', success:'Concluída', completed:'Concluída', refunded:'Estornada', credit_card:'Cartão de crédito', debit_card:'Cartão de débito', on_delivery:'Na entrega' };

export function AccountantSaleDetailsPanel({ companyId, channel, saleId, adminMode = false, onClose }: { companyId: string; channel: string; saleId: string; adminMode?: boolean; onClose?: () => void }) {
  const [data, setData] = useState<AccountantSaleDetails | null>(null);
  const [error, setError] = useState('');
  useEffect(() => {
    let active = true; setData(null); setError('');
    accountantPortalService.saleDetails(companyId, channel, saleId).then(result => { if (active) setData(result); }).catch(err => { if (active) setError(err.message); });
    return () => { active = false; };
  }, [companyId, channel, saleId]);
  if (error) return <p role="alert" className="p-4 text-red-700">{error}</p>;
  if (!data) return <p role="status" className="p-4 text-slate-500">Carregando detalhes da venda…</p>;
  return <section aria-label="Detalhes da venda" className="space-y-4 bg-blue-50/50 p-4 sm:p-6">
    <div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">Produtos e pagamentos da venda</h3><p className="text-sm text-slate-600">Cliente: {data.customerName || 'Não identificado'} · Situação: {statusLabel[data.status] || data.status || 'Não informada'}{data.paymentStatus && ` · Pagamento: ${statusLabel[data.paymentStatus] || data.paymentStatus}`}</p>{data.capturedAt && <p className="text-xs text-slate-500">Dados capturados em {new Date(data.capturedAt).toLocaleString('pt-BR')}.</p>}</div>{onClose && <button type="button" onClick={onClose} className="shrink-0 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700">Fechar</button>}</div>
    <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">Produto / SKU</th><th className="p-3">Quantidade</th><th className="p-3 text-right">Unitário</th><th className="p-3 text-right">Total do item</th></tr></thead><tbody>{data.items.map((item,index) => <tr key={index} className="border-t border-slate-100"><td className="p-3">{item.name || 'Produto sem descrição'}<span className="block text-xs text-slate-500">{item.sku}</span></td><td className="p-3">{item.quantity}</td><td className="p-3 text-right">{money(item.unitPriceCents)}</td><td className="p-3 text-right">{money(item.totalCents)}</td></tr>)}{!data.items.length && <tr><td colSpan={4} className="p-4 text-slate-500">Itens não disponíveis no registro desta venda.</td></tr>}</tbody></table></div>
    <div className="flex flex-wrap gap-5 text-sm"><span>Subtotal: {money(data.subtotalCents)}</span><span>Desconto: {money(data.discountCents)}</span><span>Frete: {money(data.shippingCents)}</span><strong>Total: {money(data.totalCents)}</strong></div>
    <div className="text-sm"><h4 className="font-semibold">Pagamentos registrados</h4>{data.payments.map((payment,index) => <p key={index}>{statusLabel[payment.method] || getPaymentLabel(payment.method)} · {money(payment.amountCents)}{payment.installments ? ` · ${payment.installments} parcela(s)` : ''}</p>)}{!data.payments.length && <p>Não informados.</p>}</div>
    {channel === 'pdv' && <div className="space-y-2 rounded-xl border border-blue-200 bg-white p-4"><h4 className="font-bold">Cupom fiscal de balcão · NFC-e</h4>{data.receipt ? <><p>Nº {data.receipt.number} · Série {data.receipt.series} · {statusLabel[data.receipt.status] || data.receipt.status}</p>{data.receipt.authorizedAt && <p className="text-xs">Autorizada em {new Date(data.receipt.authorizedAt).toLocaleString('pt-BR')}</p>}{data.receipt.available ? <AccountantFiscalFileActions companyId={companyId} saleId={saleId} /> : <p className="text-sm text-amber-800">Cupom fiscal autorizado indisponível para visualização.</p>}</> : <p className="text-sm text-slate-600">Nenhuma NFC-e de produção localizada no emissor próprio para esta venda. Confira também os documentos vinculados abaixo. Comprovante de venda não substitui o cupom fiscal.</p>}</div>}
    <div className="space-y-3"><h4 className="font-semibold">Documentos fiscais vinculados</h4>{data.documents.map(doc => <article key={doc.id} className="space-y-2 rounded-xl border border-slate-200 bg-white p-4"><p>{doc.model === '65' ? 'NFC-e' : 'NF-e'} nº {doc.number || 's/n'} · Série {doc.series || '—'} · {statusLabel[doc.status] || doc.status}</p><p className="break-all font-mono text-xs">{doc.accessKey}</p><AccountantFiscalFileActions companyId={companyId} documentId={doc.id} fileAvailable={doc.fileAvailable} adminMode={adminMode} /></article>)}{!data.documents.length && <p className="text-sm text-slate-500">Nenhum documento fiscal vinculado.</p>}</div>
  </section>;
}
