import React, { useEffect, useState } from 'react';
import { companyFiscalService, type FiscalCompany, type FiscalTaxRule, type FiscalTaxValidation } from '../../services/companyFiscalService';

const input = 'w-full rounded-lg border border-slate-300 px-3 py-2 text-sm disabled:bg-slate-100';
const button = 'rounded-lg border border-blue-300 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50 disabled:opacity-50';
const statusLabel = { draft: 'Rascunho', reviewed: 'Revisado pelo contador', approved: 'Aprovado para implementação' } as const;

export function CompanyTaxValidationPanel({ api = companyFiscalService }: { api?: typeof companyFiscalService }) {
  const [companies,setCompanies] = useState<FiscalCompany[]>([]);
  const [selected,setSelected] = useState('primary');
  const [data,setData] = useState<FiscalTaxValidation | null>(null);
  const [busy,setBusy] = useState(true);
  const [error,setError] = useState('');
  const [message,setMessage] = useState('');
  useEffect(() => { let active=true; setBusy(true); api.list().then(result => { if(!active)return; setCompanies(result.companies); setSelected(result.companies[0]?.id || ''); }).catch(err => setError(err instanceof Error ? err.message : 'Falha ao carregar empresas.')).finally(()=>active&&setBusy(false)); return()=>{active=false}; },[api]);
  useEffect(() => { if(!selected)return; let active=true; setBusy(true); setError(''); setMessage(''); api.taxValidation(selected).then(result=>active&&setData(result)).catch(err=>active&&setError(err instanceof Error?err.message:'Falha ao carregar validação contábil.')).finally(()=>active&&setBusy(false)); return()=>{active=false}; },[api,selected]);
  const patchRule=(id:string,patch:Partial<FiscalTaxRule>)=>setData(current=>current?{...current,rules:current.rules.map(rule=>rule.id===id?{...rule,...patch}:rule)}:current);
  const patchGeneral=(patch:Partial<FiscalTaxValidation['generalDecisions']>)=>setData(current=>current?{...current,generalDecisions:{...current.generalDecisions,...patch}}:current);
  const addProductRule=()=>setData(current=>current?{...current,productRules:[...current.productRules,{id:`PR${String(current.productRules.length+1).padStart(2,'0')}`,group:'',ncm:'',cest:'',origin:'',unit:'',taxTreatment:'',operations:'',effectiveFrom:'',notes:''}]}:current);
  const patchProductRule=(index:number,patch:Partial<FiscalTaxValidation['productRules'][number]>)=>setData(current=>current?{...current,productRules:current.productRules.map((rule,currentIndex)=>currentIndex===index?{...rule,...patch}:rule)}:current);
  const removeProductRule=(index:number)=>setData(current=>current?{...current,productRules:current.productRules.filter((_,currentIndex)=>currentIndex!==index)}:current);
  const save=async(status:FiscalTaxValidation['status'])=>{ if(!data)return; if(status==='approved'&&!window.confirm('Registrar esta matriz como aprovada pelo contador? Isso ainda não ativa emissão fiscal.'))return; setBusy(true);setError('');setMessage('');try{const saved=await api.saveTaxValidation(selected,{...data,status});setData(saved);setMessage(status==='approved'?'Validação contábil aprovada e registrada. Nenhuma regra foi ativada automaticamente.':'Validação contábil salva.');}catch(err){setError(err instanceof Error?err.message:'Falha ao salvar validação.')}finally{setBusy(false)}};
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 space-y-5" aria-labelledby="tax-validation-title">
    <div><h2 id="tax-validation-title" className="text-lg font-bold text-slate-800">Validação contábil das operações</h2><p className="mt-1 text-sm text-slate-600">O contador pode revisar as referências do Bling, corrigir cada cenário e registrar responsável, data e aprovação. Salvar aqui não ativa cálculo nem emissão.</p></div>
    <label className="block text-sm font-semibold">Empresa fiscal<select className={`${input} mt-1`} value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{companies.map(company=><option key={company.id} value={company.id}>{company.name} — {company.cnpj}</option>)}</select></label>
    {busy&&<p role="status">Carregando...</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{message&&<p role="status" className="text-sm text-green-700">{message}</p>}
    {data&&<>
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Referência do Bling em {new Date(data.blingReference.observedAt+'T12:00:00').toLocaleDateString('pt-BR')}:</strong> {data.blingReference.natures.map(n=>n.name+(n.defaultUse?` (${n.defaultUse})`:'' )).join(', ')}. Confirme tudo antes de aprovar.</div>
      <div className="grid gap-4 sm:grid-cols-3"><label className="text-sm">Responsável/contador<input className={input} value={data.reviewerName} onChange={e=>setData({...data,reviewerName:e.target.value})}/></label><label className="text-sm">CRC ou registro<input className={input} value={data.reviewerRegistration} onChange={e=>setData({...data,reviewerRegistration:e.target.value})}/></label><label className="text-sm">Data da revisão<input type="date" className={input} value={data.reviewedAt} onChange={e=>setData({...data,reviewedAt:e.target.value})}/></label></div>
      <label className="block text-sm">Observações gerais<textarea className={input} value={data.notes} onChange={e=>setData({...data,notes:e.target.value})}/></label>
      <fieldset className="rounded-xl border border-slate-200 p-4 space-y-3"><legend className="px-2 font-semibold text-slate-800">Decisões gerais obrigatórias</legend>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs">Regime tributário<input className={input} value={data.generalDecisions.taxRegime} onChange={e=>patchGeneral({taxRegime:e.target.value})}/></label><label className="text-xs">CRT<input className={input} value={data.generalDecisions.crt} onChange={e=>patchGeneral({crt:e.target.value})}/></label><label className="text-xs">Vigência geral<input type="date" className={input} value={data.generalDecisions.effectiveFrom} onChange={e=>patchGeneral({effectiveFrom:e.target.value})}/></label><label className="text-xs">Apuração do Simples<select className={input} value={data.generalDecisions.simplesBasis} onChange={e=>patchGeneral({simplesBasis:e.target.value})}><option value="">Selecione</option><option value="cash">Caixa</option><option value="accrual">Competência</option><option value="not_applicable">Não se aplica</option></select></label><label className="text-xs sm:col-span-2">Frete, seguro, desconto, despesas e rateio<textarea className={input} value={data.generalDecisions.freightTreatment} onChange={e=>patchGeneral({freightTreatment:e.target.value})}/></label><label className="text-xs">Exceções por produto<select className={input} value={data.generalDecisions.productExceptions} onChange={e=>patchGeneral({productExceptions:e.target.value as FiscalTaxValidation['generalDecisions']['productExceptions']})}><option value="pending">Pendente</option><option value="none">Não há exceções</option><option value="listed">Há regras específicas</option></select></label><label className="text-xs sm:col-span-2">Decisão/justificativa sobre exceções<textarea className={input} value={data.generalDecisions.productExceptionsNotes} onChange={e=>patchGeneral({productExceptionsNotes:e.target.value})}/></label></div>
      </fieldset>
      {data.generalDecisions.productExceptions==='listed'&&<section className="rounded-xl border border-slate-200 p-4 space-y-3" aria-labelledby="product-rules-title"><div className="flex items-center justify-between gap-3"><h3 id="product-rules-title" className="font-semibold text-slate-800">Regras e exceções por produto</h3><button type="button" className={button} onClick={addProductRule}>Adicionar regra</button></div>{data.productRules.length===0&&<p className="text-sm text-amber-800">Adicione ao menos uma regra antes da aprovação.</p>}{data.productRules.map((rule,index)=><article key={rule.id} className="rounded-lg bg-slate-50 p-3 space-y-2"><div className="flex justify-between gap-3"><strong className="text-sm">{rule.id}</strong><button type="button" className="text-sm font-semibold text-red-700" onClick={()=>removeProductRule(index)}>Remover</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs">Grupo/produto<input className={input} value={rule.group} onChange={e=>patchProductRule(index,{group:e.target.value})}/></label><label className="text-xs">NCM<input className={input} value={rule.ncm} onChange={e=>patchProductRule(index,{ncm:e.target.value})}/></label><label className="text-xs">CEST, se aplicável<input className={input} value={rule.cest} onChange={e=>patchProductRule(index,{cest:e.target.value})}/></label><label className="text-xs">Origem<input className={input} value={rule.origin} onChange={e=>patchProductRule(index,{origin:e.target.value})}/></label><label className="text-xs">Unidade comercial/tributável<input className={input} value={rule.unit} onChange={e=>patchProductRule(index,{unit:e.target.value})}/></label><label className="text-xs">Operações abrangidas<input className={input} value={rule.operations} onChange={e=>patchProductRule(index,{operations:e.target.value})}/></label><label className="text-xs">Vigência<input type="date" className={input} value={rule.effectiveFrom} onChange={e=>patchProductRule(index,{effectiveFrom:e.target.value})}/></label><label className="text-xs lg:col-span-2">Tributação/regra<textarea className={input} value={rule.taxTreatment} onChange={e=>patchProductRule(index,{taxTreatment:e.target.value})}/></label><label className="text-xs lg:col-span-2">Observações<textarea className={input} value={rule.notes} onChange={e=>patchProductRule(index,{notes:e.target.value})}/></label></div></article>)}</section>}
      <div className="space-y-4">{data.rules.map(rule=><article key={rule.id} className="rounded-xl border border-slate-200 p-4 space-y-3">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-800">{rule.id} — {rule.scenario}</h3><p className="text-xs text-slate-500">Origem inicial: {rule.source==='bling_reference'?'configuração observada no Bling':'escopo da migração'}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rule.used} onChange={e=>patchRule(rule.id,{used:e.target.checked})}/>Operação utilizada</label></div>
        {rule.used&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs">Modelo<input className={input} value={rule.model} onChange={e=>patchRule(rule.id,{model:e.target.value,source:'accountant'})}/></label><label className="text-xs">UF/destino<input className={input} value={rule.destinationUf} onChange={e=>patchRule(rule.id,{destinationUf:e.target.value,source:'accountant'})}/></label><label className="text-xs">Destinatário<input className={input} value={rule.recipient} onChange={e=>patchRule(rule.id,{recipient:e.target.value,source:'accountant'})}/></label><label className="text-xs">Finalidade<input className={input} value={rule.finality} onChange={e=>patchRule(rule.id,{finality:e.target.value,source:'accountant'})}/></label><label className="text-xs">CFOP<input className={input} value={rule.cfop} onChange={e=>patchRule(rule.id,{cfop:e.target.value,source:'accountant'})}/></label><label className="text-xs">CSOSN/CST ICMS<input className={input} value={rule.icmsCode} onChange={e=>patchRule(rule.id,{icmsCode:e.target.value,source:'accountant'})}/></label><label className="text-xs lg:col-span-2">ICMS, ST, FCP e DIFAL<textarea className={input} value={rule.icmsTreatment} onChange={e=>patchRule(rule.id,{icmsTreatment:e.target.value,source:'accountant'})}/></label><label className="text-xs">PIS/COFINS<textarea className={input} value={rule.pisCofins} onChange={e=>patchRule(rule.id,{pisCofins:e.target.value,source:'accountant'})}/></label><label className="text-xs">IPI<textarea className={input} value={rule.ipi} onChange={e=>patchRule(rule.id,{ipi:e.target.value,source:'accountant'})}/></label><label className="text-xs">Benefício/informação adicional<textarea className={input} value={rule.benefit} onChange={e=>patchRule(rule.id,{benefit:e.target.value,source:'accountant'})}/></label><label className="text-xs">Vigência<input type="date" className={input} value={rule.effectiveFrom} onChange={e=>patchRule(rule.id,{effectiveFrom:e.target.value,source:'accountant'})}/></label><label className="text-xs sm:col-span-2 lg:col-span-3">Observações/procedimento<textarea className={input} value={rule.notes} onChange={e=>patchRule(rule.id,{notes:e.target.value,source:'accountant'})}/></label></div>}
      </article>)}</div>
      <div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">Estado: {statusLabel[data.status]}</span><button className={button} disabled={busy} onClick={()=>save('draft')}>Salvar rascunho</button><button className={button} disabled={busy} onClick={()=>save('reviewed')}>Marcar como revisado</button><button className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={busy} onClick={()=>save('approved')}>Aprovar para implementação</button></div>
    </>}
  </section>;
}
