import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ExternalLink, MessageCircle, Plus } from 'lucide-react';
import { createPurchaseSupplier, getPurchaseSuppliers } from '../../../services/purchaseQueueService.js';

const websiteHref = (value: string) => /^https?:\/\//i.test(value) ? value : `https://${value}`;
const whatsappHref = (value: string) => `https://wa.me/${String(value || '').replace(/\D/g, '')}`;

export const PurchaseSuppliersPage: React.FC = () => {
  const [suppliers, setSuppliers] = React.useState<any[]>([]); const [error, setError] = React.useState(''); const [saving, setSaving] = React.useState(false); const [form, setForm] = React.useState({ name: '', website: '', whatsapp: '' });
  const load = React.useCallback(async () => { try { setSuppliers(await getPurchaseSuppliers()); } catch { setError('Não foi possível carregar fornecedores.'); } }, []);
  React.useEffect(() => { load(); }, [load]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await createPurchaseSupplier({ name: form.name, websiteUrl: form.website, whatsapp: form.whatsapp }); setForm({ name: '', website: '', whatsapp: '' }); await load(); } catch (err: any) { setError(err?.message || 'Não foi possível salvar fornecedor.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-5xl space-y-6"><Link to="/admin/compras" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={16}/> Voltar para compras</Link><div><h2 className="text-3xl font-bold">Fornecedores</h2><p className="mt-1 text-slate-500">Cadastre os canais de consulta para usar nos orçamentos.</p></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">Novo fornecedor</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><input required value={form.name} onChange={e => setForm(v => ({ ...v, name: e.target.value }))} placeholder="Nome" className="rounded-xl border border-slate-300 px-3 py-2"/><input value={form.website} onChange={e => setForm(v => ({ ...v, website: e.target.value }))} placeholder="Site (ex.: fornecedor.com)" className="rounded-xl border border-slate-300 px-3 py-2"/><input value={form.whatsapp} onChange={e => setForm(v => ({ ...v, whatsapp: e.target.value }))} placeholder="WhatsApp com DDD" className="rounded-xl border border-slate-300 px-3 py-2"/></div><button disabled={saving} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 font-bold text-white"><Plus size={17}/> Cadastrar fornecedor</button></form><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Fornecedor</th><th className="px-5 py-4">Atalhos</th></tr></thead><tbody className="divide-y divide-slate-100">{suppliers.map(supplier => <tr key={supplier.id}><td className="px-5 py-4 font-bold text-slate-900">{supplier.name}</td><td className="px-5 py-4"><div className="flex gap-3">{supplier.website_url && <a target="_blank" rel="noreferrer" href={websiteHref(supplier.website_url)} className="inline-flex items-center gap-1 font-bold text-blue-700"><ExternalLink size={15}/> Site</a>}{supplier.whatsapp && <a target="_blank" rel="noreferrer" href={whatsappHref(supplier.whatsapp)} className="inline-flex items-center gap-1 font-bold text-emerald-700"><MessageCircle size={15}/> WhatsApp</a>}</div></td></tr>)}{!suppliers.length && <tr><td colSpan={2} className="px-5 py-10 text-center text-slate-500">Nenhum fornecedor cadastrado.</td></tr>}</tbody></table></div></div>;
};
