import React from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, ExternalLink, MessageCircle, Store, Trophy } from 'lucide-react';
import { createPurchaseQuote, getPurchaseQueueItem, getPurchaseSuppliers, markPurchaseQueueItemAsPurchased } from '../../../services/purchaseQueueService.js';

const money = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format((Number(cents) || 0) / 100);
const centsFromInput = (value: string) => Math.round(Number(String(value).replace(',', '.')) * 100);
const websiteHref = (value: string) => value && /^https?:\/\//i.test(value) ? value : `https://${value}`;
const whatsappHref = (value: string) => `https://wa.me/${String(value || '').replace(/\D/g, '')}`;

export const PurchaseQuotePage: React.FC = () => {
  const { itemId = '' } = useParams(); const navigate = useNavigate();
  const [item, setItem] = React.useState<any>(null); const [suppliers, setSuppliers] = React.useState<any[]>([]); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState(''); const [saving, setSaving] = React.useState(false);
  const [form, setForm] = React.useState({ supplierId: '', price: '', quantity: '1', notes: '' }); const [selectedQuoteId, setSelectedQuoteId] = React.useState(''); const [purchaseQuantity, setPurchaseQuantity] = React.useState('1');
  const load = React.useCallback(async () => { setLoading(true); try { const [next, supplierRows] = await Promise.all([getPurchaseQueueItem(itemId), getPurchaseSuppliers()]); setItem(next); setSuppliers(supplierRows); if (next?.lowest_quote && !selectedQuoteId) { setSelectedQuoteId(next.lowest_quote.id); setPurchaseQuantity(String(next.lowest_quote.quantity || 1)); } if (!next) setError('Item de compra não encontrado.'); } catch { setError('Não foi possível carregar os orçamentos.'); } finally { setLoading(false); } }, [itemId, selectedQuoteId]);
  React.useEffect(() => { load(); }, [load]);
  const selectedSupplier = suppliers.find(supplier => supplier.id === form.supplierId);
  const quoteSupplier = (quote: any) => suppliers.find(supplier => supplier.id === quote.supplier_id);
  const addQuote = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await createPurchaseQuote({ queueItemId: itemId, supplierId: form.supplierId, unitPriceCents: centsFromInput(form.price), quantity: Number(form.quantity), notes: form.notes }); setForm({ supplierId: '', price: '', quantity: '1', notes: '' }); await load(); } catch (err: any) { setError(err?.message || 'Não foi possível registrar o orçamento.'); } finally { setSaving(false); } };
  const confirm = async () => { setSaving(true); setError(''); try { await markPurchaseQueueItemAsPurchased({ queueItemId: itemId, quoteId: selectedQuoteId, quantity: Number(purchaseQuantity) }); navigate('/admin/compras'); } catch (err: any) { setError(err?.message || 'Não foi possível confirmar a compra.'); } finally { setSaving(false); } };
  if (loading) return <div className="p-8 text-slate-500">Carregando orçamento...</div>;
  if (!item) return <div className="space-y-4"><Link to="/admin/compras" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={16}/> Voltar para compras</Link><p className="rounded-xl bg-rose-50 p-4 text-rose-800">{error || 'Item não encontrado.'}</p></div>;
  const selected = item.quotes?.find((quote: any) => quote.id === selectedQuoteId);
  return <div className="mx-auto max-w-5xl space-y-6 animate-in fade-in duration-300"><Link to="/admin/compras" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft size={16}/> Voltar para compras</Link>
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Página de orçamento</p><h2 className="mt-1 text-3xl font-bold text-slate-900">{item.model}</h2><div className="mt-3 flex flex-wrap gap-3 text-sm text-slate-600"><span>SKU: <strong>{item.sku || 'não informado'}</strong></span><span>Vendas hoje: <strong>{item.last_digest_quantity || 0}</strong></span><span>Estoque atual: <strong>{item.current_stock || 0}</strong></span></div></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Store className="text-violet-700" size={20}/><h3 className="font-bold">Adicionar cotação</h3></div><Link to="/admin/compras/fornecedores" className="text-sm font-bold text-violet-700">Cadastrar fornecedor</Link></div><p className="mt-1 text-sm text-slate-500">Selecione a loja cadastrada; seus atalhos ficam disponíveis aqui.</p><form onSubmit={addQuote} className="mt-5 grid gap-3"><select required value={form.supplierId} onChange={e => setForm(v => ({ ...v, supplierId: e.target.value }))} className="rounded-xl border border-slate-300 bg-white px-3 py-2"><option value="">Selecione o fornecedor</option>{suppliers.map(supplier => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select>{selectedSupplier && <div className="flex flex-wrap gap-2">{selectedSupplier.website_url && <a target="_blank" rel="noreferrer" href={websiteHref(selectedSupplier.website_url)} className="inline-flex items-center gap-1 rounded-lg border border-blue-200 px-3 py-1.5 text-xs font-bold text-blue-700"><ExternalLink size={14}/> Abrir site</a>}{selectedSupplier.whatsapp && <a target="_blank" rel="noreferrer" href={whatsappHref(selectedSupplier.whatsapp)} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 px-3 py-1.5 text-xs font-bold text-emerald-700"><MessageCircle size={14}/> WhatsApp</a>}</div>}<div className="grid grid-cols-2 gap-3"><input required min="0" step="0.01" inputMode="decimal" value={form.price} onChange={e => setForm(v => ({ ...v, price: e.target.value }))} placeholder="Preço unitário (R$)" className="rounded-xl border border-slate-300 px-3 py-2"/><input required min="1" type="number" value={form.quantity} onChange={e => setForm(v => ({ ...v, quantity: e.target.value }))} placeholder="Quantidade" className="rounded-xl border border-slate-300 px-3 py-2"/></div><textarea value={form.notes} onChange={e => setForm(v => ({ ...v, notes: e.target.value }))} placeholder="Observação (opcional)" className="min-h-24 rounded-xl border border-slate-300 px-3 py-2"/><button disabled={saving} className="rounded-xl bg-violet-700 px-4 py-2.5 font-bold text-white disabled:opacity-60">Salvar orçamento</button></form></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Trophy className="text-amber-500" size={20}/><h3 className="font-bold">Menor preço</h3></div>{item.lowest_quote ? <><p className="mt-4 text-3xl font-black text-emerald-700">{money(item.lowest_quote.unit_price_cents)}</p><p className="text-sm text-slate-600">na {item.lowest_quote.supplier_name}</p></> : <p className="mt-4 text-sm text-slate-500">Ainda não há cotações.</p>}</section></div>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-4"><h3 className="font-bold">Cotações registradas ({item.quote_count || 0})</h3></div><div className="divide-y divide-slate-100">{item.quotes?.map((quote: any, index: number) => { const supplier = quoteSupplier(quote); return <label key={quote.id} className={`flex cursor-pointer items-center gap-4 px-6 py-4 ${index === 0 ? 'bg-emerald-50' : ''}`}><input type="radio" name="quote" checked={selectedQuoteId === quote.id} onChange={() => { setSelectedQuoteId(quote.id); setPurchaseQuantity(String(quote.quantity || 1)); }}/><div className="min-w-0 flex-1"><p className="font-bold">{quote.supplier_name} {index === 0 && <span className="ml-2 rounded-full bg-emerald-100 px-2 py-0.5 text-xs text-emerald-700">Menor preço</span>}</p><p className="text-sm text-slate-500">{quote.quantity} unidade(s){quote.notes ? ` · ${quote.notes}` : ''}</p>{supplier && <div className="mt-1 flex gap-2">{supplier.website_url && <a onClick={e => e.stopPropagation()} target="_blank" rel="noreferrer" href={websiteHref(supplier.website_url)} className="text-xs font-bold text-blue-700">Site ↗</a>}{supplier.whatsapp && <a onClick={e => e.stopPropagation()} target="_blank" rel="noreferrer" href={whatsappHref(supplier.whatsapp)} className="text-xs font-bold text-emerald-700">WhatsApp ↗</a>}</div>}</div><p className="font-black">{money(quote.unit_price_cents)}</p></label>; })}{!item.quotes?.length && <p className="px-6 py-8 text-sm text-slate-500">Cadastre a primeira loja acima.</p>}</div></section>
    {selected && <section className="flex flex-col gap-3 rounded-3xl border border-emerald-200 bg-emerald-50 p-5 md:flex-row md:items-end"><div className="flex-1"><p className="font-bold text-emerald-950">Confirmar compra em {selected.supplier_name}</p><p className="text-sm text-emerald-800">Valor unitário: {money(selected.unit_price_cents)}</p></div><label className="text-sm font-semibold text-emerald-950">Quantidade efetivamente comprada<input type="number" min="1" value={purchaseQuantity} onChange={e => setPurchaseQuantity(e.target.value)} className="mt-1 block w-40 rounded-xl border border-emerald-300 bg-white px-3 py-2"/></label><button disabled={saving} onClick={confirm} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-2.5 font-bold text-white"><CheckCircle2 size={18}/> Marcar como comprado</button></section>}
  </div>;
};
