CREATE TABLE signed_warranty_documents (
  id CHAR(36) PRIMARY KEY,
  company_id VARCHAR(255) NULL,
  sale_id VARCHAR(255) NULL,
  customer_id VARCHAR(255) NULL,
  sale_code VARCHAR(8) NULL,
  source ENUM('sale_screen','synology_direct') NOT NULL,
  status ENUM('received','processing','available','error','replaced') NOT NULL DEFAULT 'received',
  original_file_name VARCHAR(255) NOT NULL,
  image_path VARCHAR(600) NULL,
  pdf_path VARCHAR(600) NULL,
  image_mime_type VARCHAR(80) NULL,
  image_size_bytes BIGINT NULL,
  image_sha256 CHAR(64) NULL,
  pdf_sha256 CHAR(64) NULL,
  error_code VARCHAR(80) NULL,
  error_message TEXT NULL,
  version_number INT NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  active_sale_key VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN is_active = 1 THEN sale_id ELSE NULL END) STORED,
  dedupe_company_key VARCHAR(255) GENERATED ALWAYS AS (COALESCE(company_id, '__unassigned__')) STORED,
  uploaded_by_customer_id VARCHAR(255) NULL,
  processed_at DATETIME NULL,
  discarded_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_signed_warranty_sale_active (sale_id, is_active),
  INDEX idx_signed_warranty_status (status, created_at),
  INDEX idx_signed_warranty_sale_code (sale_code),
  UNIQUE KEY uniq_signed_warranty_active_sale (active_sale_key),
  UNIQUE KEY uniq_signed_warranty_sale_version (sale_id, version_number),
  UNIQUE KEY uniq_signed_warranty_company_hash (dedupe_company_key, image_sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
