CREATE TABLE signed_warranty_documents (
  id CHAR(36) PRIMARY KEY,
  company_id VARCHAR(255) NULL,
  sale_id VARCHAR(255) NULL,
  customer_id VARCHAR(255) NULL,
  sale_code VARCHAR(8) NULL,
  source ENUM('sale_screen','synology_direct') NOT NULL,
  status ENUM('received','processing','available','error','replaced') NOT NULL DEFAULT 'received',
  original_file_name VARCHAR(255) NOT NULL,
  image_path VARCHAR(600) NULL,
  pdf_path VARCHAR(600) NULL,
  image_mime_type VARCHAR(80) NULL,
  image_size_bytes BIGINT NULL,
  image_sha256 CHAR(64) NULL,
  pdf_sha256 CHAR(64) NULL,
  error_code VARCHAR(80) NULL,
  error_message TEXT NULL,
  version_number INT NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  uploaded_by_customer_id VARCHAR(255) NULL,
  processed_at DATETIME NULL,
  discarded_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_signed_warranty_sale_active (sale_id, is_active),
  INDEX idx_signed_warranty_status (status, created_at),
  INDEX idx_signed_warranty_sale_code (sale_code),
  UNIQUE KEY uniq_signed_warranty_company_hash (company_id, image_sha256)
);
