CREATE TABLE IF NOT EXISTS marketing_approval_requests (
  id CHAR(36) PRIMARY KEY,
  channel VARCHAR(40) NOT NULL DEFAULT 'instagram',
  action_type VARCHAR(60) NOT NULL,
  title VARCHAR(255) NOT NULL,
  target_type VARCHAR(60) NOT NULL,
  target_id VARCHAR(255) NULL,
  target_name VARCHAR(255) NULL,
  status ENUM('pending', 'approved', 'rejected', 'executing', 'succeeded', 'failed', 'cancelled', 'expired') NOT NULL DEFAULT 'pending',
  execution_mode ENUM('vps_meta_api', 'lenovo_chrome', 'manual') NOT NULL DEFAULT 'vps_meta_api',
  current_state JSON NULL,
  proposed_state JSON NOT NULL,
  evidence JSON NULL,
  financial_impact JSON NULL,
  success_criteria JSON NULL,
  rollback_plan TEXT NOT NULL,
  execution_payload JSON NULL,
  execution_result JSON NULL,
  requested_by VARCHAR(80) NULL,
  requested_by_label VARCHAR(255) NULL,
  reviewed_by VARCHAR(80) NULL,
  review_note TEXT NULL,
  runner_id VARCHAR(120) NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  approval_expires_at DATETIME NULL,
  approved_at DATETIME NULL,
  rejected_at DATETIME NULL,
  execution_started_at DATETIME NULL,
  executed_at DATETIME NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_marketing_approval_idempotency (idempotency_key),
  INDEX idx_marketing_approval_queue (status, created_at),
  INDEX idx_marketing_approval_channel (channel, status),
  INDEX idx_marketing_approval_expiry (status, approval_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS marketing_approval_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  approval_id CHAR(36) NOT NULL,
  event_type VARCHAR(60) NOT NULL,
  actor_id VARCHAR(80) NULL,
  actor_label VARCHAR(255) NULL,
  details JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_marketing_approval_events_request (approval_id, id),
  INDEX idx_marketing_approval_events_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
