CREATE TABLE IF NOT EXISTS smartphone_brand_price_margins (
  id CHAR(36) NOT NULL,
  brand_id CHAR(36) NOT NULL,
  company_id CHAR(36) NULL,
  retail_margin_cents INT NOT NULL DEFAULT 0,
  reseller_margin_cents INT NOT NULL DEFAULT 0,
  wholesale_margin_cents INT NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY idx_smartphone_brand_margin_unique (company_id, brand_id),
  INDEX idx_smartphone_brand_margin_company (company_id),
  CONSTRAINT fk_smartphone_brand_margin_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smartphone_photo_intakes (
  id CHAR(36) NOT NULL,
  company_id CHAR(36) NULL,
  batch_id CHAR(36) NULL,
  photo_private_path VARCHAR(1000) NOT NULL,
  photo_sha256 CHAR(64) NOT NULL,
  status VARCHAR(48) NOT NULL DEFAULT 'uploaded',
  ai_model VARCHAR(80) NOT NULL DEFAULT 'gpt-5.6-luna',
  detected_brand VARCHAR(160) NULL,
  detected_model VARCHAR(255) NULL,
  detected_color VARCHAR(120) NULL,
  detected_ram VARCHAR(32) NULL,
  detected_storage VARCHAR(32) NULL,
  detected_serial VARCHAR(120) NULL,
  detected_imei_1 VARCHAR(20) NULL,
  detected_imei_2 VARCHAR(20) NULL,
  detected_ean VARCHAR(20) NULL,
  detected_product_code VARCHAR(120) NULL,
  matched_brand_id CHAR(36) NULL,
  matched_model_id CHAR(36) NULL,
  matched_product_id CHAR(36) NULL,
  price_cost INT NULL,
  price_retail INT NULL,
  price_reseller INT NULL,
  price_wholesale INT NULL,
  prices_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  extracted_data JSON NULL,
  validation_errors JSON NULL,
  validation_warnings JSON NULL,
  ai_input_tokens INT NOT NULL DEFAULT 0,
  ai_output_tokens INT NOT NULL DEFAULT 0,
  ai_cost_usd DECIMAL(14,8) NOT NULL DEFAULT 0,
  ai_input_rate_usd_per_1m DECIMAL(14,8) NOT NULL DEFAULT 0.20,
  ai_output_rate_usd_per_1m DECIMAL(14,8) NOT NULL DEFAULT 1.20,
  retry_count INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  created_by CHAR(36) NULL,
  reviewed_by CHAR(36) NULL,
  unit_id CHAR(36) NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_smartphone_photo_intake_status (status, created_at),
  UNIQUE KEY idx_smartphone_photo_intake_hash (company_id, photo_sha256),
  INDEX idx_smartphone_photo_intake_company (company_id, status),
  INDEX idx_smartphone_photo_intake_model (matched_model_id),
  INDEX idx_smartphone_photo_intake_imei_1 (detected_imei_1),
  INDEX idx_smartphone_photo_intake_serial (detected_serial)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_usage_events (
  id CHAR(36) NOT NULL,
  company_id CHAR(36) NULL,
  feature VARCHAR(80) NOT NULL,
  reference_id CHAR(36) NULL,
  provider VARCHAR(40) NOT NULL DEFAULT 'openai',
  model VARCHAR(80) NOT NULL,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  input_rate_usd_per_1m DECIMAL(14,8) NOT NULL DEFAULT 0,
  output_rate_usd_per_1m DECIMAL(14,8) NOT NULL DEFAULT 0,
  estimated_cost_usd DECIMAL(14,8) NOT NULL DEFAULT 0,
  request_id VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_ai_usage_feature_created (feature, created_at),
  INDEX idx_ai_usage_reference (reference_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE units
  ADD COLUMN IF NOT EXISTS intake_photo_path VARCHAR(1000) NULL,
  ADD COLUMN IF NOT EXISTS intake_id CHAR(36) NULL;

CREATE INDEX IF NOT EXISTS idx_units_intake_id ON units(intake_id);
