import React, {useEffect,useState} from 'react';
import {mercadoLivreService} from '../../../services/mercadoLivreService';

export default function MercadoLivreCategorySection({value,onChange}:{value:any;onChange:(value:any)=>void}) {
  const [id,setId]=useState(value?.category_id || ''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{setId(value?.category_id || '');},[value?.category_id]);
  const load=async()=>{setBusy(true);setError('');try{const data=await mercadoLivreService.getCategoryRequirements(id);if(data.category?.id!==id || !Array.isArray(data.attributes))throw Error('Ficha oficial indisponível.');onChange({category_id:id,category_name:data.category.name,attributes:data.attributes,fetched_at:new Date().toISOString()});}catch(e){setError(e instanceof Error?e.message:'Falha na consulta.');}finally{setBusy(false);}};
  return <section className="bg-white rounded-xl border p-5 space-y-3" aria-label="Atributos Mercado Livre da categoria"><h3 className="font-semibold">Ficha da categoria • Mercado Livre</h3><p className="text-sm">Vincule esta categoria à categoria oficial. Os campos ficam disponíveis no cadastro de todos os produtos desta categoria; os valores são preenchidos por produto ou modelo.</p><label className="block">Categoria Mercado Livre (código MLB)<input className="border rounded p-2 block" value={id} onChange={e=>setId(e.target.value.trim().toUpperCase())}/></label><button type="button" disabled={busy || !/^MLB\d+$/.test(id)} onClick={load} className="border rounded p-2">{busy?'Consultando…':'Importar ficha oficial para esta categoria'}</button>{error && <p role="alert" className="text-red-700">{error}</p>}{value?.attributes && <><p>{value.category_name} ({value.category_id}) • {value.attributes.length} atributos. Salve a categoria para guardar a ficha no sistema.</p><details><summary>Ver todos os campos da categoria</summary><ul className="text-sm">{value.attributes.map((a:any)=><li key={a.id}>{a.name} ({a.id}) • {a.tags?.read_only?'Gerenciado pelo Mercado Livre':a.tags?.required?'Obrigatório':'Opcional/condicional'}</li>)}</ul></details></>}</section>;
}
