import { useEffect, useMemo, useState, useRef } from 'react';
import { AccountantSaleDetailsPanel } from '../../components/company/AccountantSaleDetailsPanel';
import { AccountantFiscalFileActions } from '../../components/company/AccountantFiscalFileActions';
import { formatReferenceNumber } from '../../utils/referenceNumber';
import { lastTwelveMonths, revenueView, revenueFilterLabels, type RevenueFilter } from '../../services/accountantRevenueView';
import { Building2, FileCheck2, LogOut, ReceiptText, RefreshCw } from 'lucide-react';
import { useVpsAuth } from '../../contexts/VpsAuthContext';
import { CompanyTaxValidationPanel } from '../../components/company/CompanyTaxValidationPanel';
import { AccountantNfceSequencePanel } from '../../components/company/AccountantNfceSequencePanel';
import { FiscalDocumentReviewPanel } from '../../components/company/FiscalDocumentReviewPanel';
import { accountantPortalService, accountantAccessAdminService, type AccountantCompany, type AccountantRevenueReport, type FiscalCancellationAssessment, type FiscalCancellationAlert } from '../../services/accountantPortalService';

const money = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format((Number(cents) || 0) / 100);
const reportDate = (value: string) => new Date(value).toLocaleDateString('pt-BR', { timeZone: 'UTC' });
const fiscalLabel: Record<string, string> = {
  invoiced: 'Com documento autorizado', no_invoice_confirmed: 'Sem nota confirmado', reconciliation_pending: 'Pendente de conciliação',
  cancelled: 'Cancelada/estornada', operational_pending: 'Pendente operacional',
};
const channelLabel: Record<string, string> = { shopee: 'Shopee', tiktok: 'TikTok Shop', unidentified: 'Canal não identificado', pdv: 'PDV', online: 'Site' };
const reviewLabel: Record<string, string> = {
  amount_difference: 'Valor do pedido diferente da nota',
  operational_pending_with_document: 'Status capturado como pendente; conferir situação atual do pedido',
  cancelled_with_document: 'Status capturado como cancelado; conferir situação atual do pedido',
  sale_outside_period: 'Pedido criado fora do período selecionado; exibido somente para conferência',
};

export function RevenuePanel({ adminMode = false }: { adminMode?: boolean }) {
  const [expandedSale, setExpandedSale] = useState('');
  const [saleSearch, setSaleSearch] = useState('');
  const [visibleSaleCount, setVisibleSaleCount] = useState(50);
  const closeSaleRef = useRef<HTMLButtonElement>(null);
  const loadVersion = useRef(0);
  const [companies, setCompanies] = useState<AccountantCompany[]>([]);
  const [companyId, setCompanyId] = useState('');
  const [initialPeriod] = useState(lastTwelveMonths);
  const [from, setFrom] = useState(initialPeriod.from);
  const [to, setTo] = useState(initialPeriod.to);
  const [filter, setFilter] = useState<RevenueFilter>('all');
  const [report, setReport] = useState<AccountantRevenueReport | null>(null);
  const view = useMemo(() => report ? revenueView(report, filter) : null, [report, filter]);
  const selectedSale = view?.sales.find(sale => `${sale.channel}:${sale.externalSaleId}` === expandedSale);
  const matchingSales = useMemo(() => {
    const term = saleSearch.trim().toLocaleLowerCase('pt-BR');
    return view?.sales.filter(sale => !term || `${sale.externalSaleId} ${channelLabel[sale.channel] || sale.channel} ${fiscalLabel[sale.fiscalState] || sale.fiscalState}`.toLocaleLowerCase('pt-BR').includes(term)) || [];
  }, [view, saleSearch]);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState('');
  const [selectedDocumentId, setSelectedDocumentId] = useState('');
  const [sefazBusy, setSefazBusy] = useState(false);
  const [sefazError, setSefazError] = useState('');
  const [sefazResult, setSefazResult] = useState<{ cStat: string; reason: string; situation: string; checkedAt: string } | null>(null);
  const [cancellationResult, setCancellationResult] = useState<FiscalCancellationAssessment | null>(null);
  const [cancellationBusy, setCancellationBusy] = useState(false);
  const [cancellationError, setCancellationError] = useState('');
  const [cancellationAlerts, setCancellationAlerts] = useState<FiscalCancellationAlert[]>([]);
  useEffect(() => {
    if (!expandedSale) return;
    closeSaleRef.current?.focus();
    const onEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') setExpandedSale(''); };
    window.addEventListener('keydown', onEscape);
    return () => window.removeEventListener('keydown', onEscape);
  }, [expandedSale]);
  useEffect(() => { accountantPortalService.list().then(result => { setCompanies(result.companies); setCompanyId(result.companies[0]?.id || ''); }).catch(err => setError(err.message)).finally(() => setBusy(false)); }, []);
  const load = async (period = { from, to }) => {
    if (!companyId) return;
    const version = ++loadVersion.current;
    setExpandedSale(''); setVisibleSaleCount(50); setReport(null);
    setBusy(true); setError(''); setSelectedDocumentId(''); setSefazResult(null); setSefazError(''); setCancellationResult(null); setCancellationError('');
    try {
      const nextReport = await accountantPortalService.revenue(companyId, period.from, period.to);
      if (version !== loadVersion.current) return;
      setReport(nextReport);
      if (adminMode) {
        const alerts = await accountantAccessAdminService.cancellationAlerts(companyId);
        if (version === loadVersion.current) setCancellationAlerts(alerts.alerts);
      }
    } catch (err) { if (version === loadVersion.current) setError(err instanceof Error ? err.message : 'Falha ao carregar faturamento.'); } finally { if (version === loadVersion.current) setBusy(false); }
  };
  useEffect(() => { if (companyId) void load(); }, [companyId]);
  const consultSefaz = async () => {
    if (!companyId || !selectedDocumentId) return;
    setSefazBusy(true); setSefazError(''); setSefazResult(null);
    try { setSefazResult(await accountantPortalService.sefazStatus(companyId, selectedDocumentId)); }
    catch (err) { setSefazError(err instanceof Error ? err.message : 'Falha ao consultar a SEFAZ.'); }
    finally { setSefazBusy(false); }
  };
  const assessCancellation = async () => {
    if (!adminMode || !companyId || !selectedDocumentId) return;
    setCancellationBusy(true); setCancellationError(''); setCancellationResult(null);
    try { setCancellationResult(await accountantAccessAdminService.cancellationAssessment(companyId, selectedDocumentId)); }
    catch (err) { setCancellationError(err instanceof Error ? err.message : 'Falha ao conferir o cancelamento.'); }
    finally { setCancellationBusy(false); }
  };
  return <section className="space-y-5">
    {adminMode && cancellationAlerts.length > 0 && <aside role="alert" className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-bold">Atenção a pedidos com NF-e emitida</h2><p className="text-sm">Pedidos em aberto não são cancelados automaticamente. Falhas e situações incertas exigem conferência.</p><ul className="mt-2 list-inside list-disc text-sm">{cancellationAlerts.map(alert => <li key={alert.documentId}>{channelLabel[alert.channel] || alert.channel} · pedido {alert.orderReference} · NF-e {alert.documentNumber || 's/n'} · {alert.state === 'open_alert' ? `em aberto (${alert.marketplaceStatus})` : `conferir ${alert.state}: ${alert.reason || 'sem detalhe'}`}</li>)}</ul></aside>}
    {adminMode && report?.reviewSales.some(sale => sale.reviewReasons?.includes('operational_pending_with_document')) && <aside role="alert" className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-bold">Pedidos registrados em aberto com nota emitida</h2><p className="text-sm">Este aviso usa o último status salvo no sistema. Confira a situação atual no marketplace antes de qualquer ação fiscal; não há cancelamento automático para pedido em aberto.</p></aside>}
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-3 md:grid-cols-4"><label className="text-sm font-semibold">Empresa<select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={companyId} onChange={event => setCompanyId(event.target.value)}>{companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="text-sm font-semibold">De<input type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="text-sm font-semibold">Até<input type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={to} onChange={event => setTo(event.target.value)} /></label><button type="button" onClick={() => void load()} disabled={busy || !companyId || !from || !to || from > to} className="mt-6 inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 font-semibold text-white disabled:opacity-50"><RefreshCw size={17} className={busy ? 'animate-spin' : ''}/>Atualizar</button></div></div>
    <div className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-5"><label className="text-sm font-semibold">Mostrar faturamento<select className="mt-1 block rounded-lg border border-slate-300 px-3 py-2" value={filter} onChange={event => { setFilter(event.target.value as RevenueFilter); setExpandedSale(''); }}>{Object.entries(revenueFilterLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" disabled={busy || !companyId} className="rounded-lg border border-blue-300 px-4 py-2 text-sm font-semibold text-blue-700 disabled:opacity-50" onClick={() => { const period = lastTwelveMonths(); setFrom(period.from); setTo(period.to); void load(period); }}>Últimos 12 meses</button><p className="text-xs text-slate-500">Os 12 meses incluem o mês atual até hoje. Use De e Até para consultar qualquer período.</p></div>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    {report && <nav aria-label="Seções do faturamento" className="flex flex-wrap gap-2 text-sm font-semibold"><a href="#resumo-faturamento" className="rounded-full border border-slate-200 bg-white px-3 py-2 text-blue-700 hover:bg-blue-50">Resumo</a><a href="#vendas" className="rounded-full border border-slate-200 bg-white px-3 py-2 text-blue-700 hover:bg-blue-50">Vendas</a><a href="#notas-importadas" className="rounded-full border border-slate-200 bg-white px-3 py-2 text-blue-700 hover:bg-blue-50">Notas importadas</a><a href="#conferencias" className="rounded-full border border-slate-200 bg-white px-3 py-2 text-blue-700 hover:bg-blue-50">Conferências</a></nav>}
    {report && <>
      {!report.coverage.available && <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{report.coverage.reason}</p>}
      {report.coverage.note && <details className="rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700"><summary className="cursor-pointer font-semibold">Como os dados deste relatório são obtidos</summary><p className="mt-2">{report.coverage.note} As datas seguem o dia usado pelo filtro. O relatório não calcula impostos.</p></details>}
      <aside className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950" role="note"><strong>Cobertura fiscal ainda não conferida:</strong> há {report.documentTotals.authorizedDocumentCount} nota(s) autorizada(s) cadastrada(s) neste período.{report.documents.length > 0 && ` As notas cadastradas vão de ${reportDate(report.documents[report.documents.length - 1].issuedAt)} a ${reportDate(report.documents[0].issuedAt)}.`} Esse número não representa todas as notas emitidas no Bling enquanto o histórico não for importado. Vendas sem nota vinculada aqui continuam pendentes de conciliação, não confirmadas como vendas sem nota.{adminMode && ' Confira a prévia e importe os dias pendentes em “Acessos e importação”.'}</aside>
      <div id="resumo-faturamento" className="scroll-mt-4" />
      {view && <section aria-label="Somatório do faturamento" className="space-y-4 rounded-2xl border border-blue-200 bg-blue-50 p-5"><div><p className="font-semibold text-blue-900">{revenueFilterLabels[filter]} · {reportDate(report.period.from)} a {reportDate(report.period.to)}</p><p className="mt-2 text-3xl font-black text-blue-950">{money(view.totalCents)}</p><p className="mt-1 text-sm text-blue-900">{view.count} {view.fiscal ? 'documento(s) autorizado(s) registrado(s) no sistema, pela data de emissão. Cancelados excluídos.' : 'venda(s) concluída(s), pela data da venda. Canceladas e pendentes operacionais excluídas.'}</p></div><p className="text-sm text-slate-700">{view.fiscal ? 'Este quadro considera apenas notas importadas ou emitidas pelo sistema. Mês sem registro não comprova faturamento zero; confira a cobertura fiscal com o contador. ' : ''}Filtro de acompanhamento, sem cálculo de impostos. Venda sem nota não é automaticamente isenta; a apuração deve ser conferida pelo contador. Os totais de documentos e de vendas são bases distintas e não devem ser somados.</p><div className="overflow-x-auto rounded-xl border border-blue-100 bg-white"><table className="min-w-full text-sm"><caption className="p-3 text-left font-semibold">Registros por mês, tipo e canal</caption><thead className="bg-slate-50 text-left"><tr><th className="px-4 py-2">Mês</th><th className="px-4 py-2">Tipo</th><th className="px-4 py-2">Canal</th><th className="px-4 py-2 text-right">Quantidade</th><th className="px-4 py-2 text-right">Valor</th></tr></thead><tbody>{view.months.length === 0 && <tr><td colSpan={5} className="px-4 py-5 text-center text-slate-500">Nenhum registro encontrado para este filtro e período.</td></tr>}{view.months.map(row => <tr key={`${row.month}:${row.type}:${row.channel}`} className="border-t border-slate-100"><td className="px-4 py-2">{row.month.slice(5)}/{row.month.slice(0,4)}</td><td className="px-4 py-2 font-semibold">{row.type}</td><td className="px-4 py-2">{channelLabel[row.channel] || 'Canal não identificado'}</td><td className="px-4 py-2 text-right">{row.count}</td><td className="px-4 py-2 text-right">{money(row.totalCents)}</td></tr>)}</tbody></table></div></section>}
      <section id="conferencias" className="scroll-mt-4 overflow-hidden rounded-2xl border border-amber-200 bg-white"><div className="border-b border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Pedidos e notas para conferir ({report.reviewSales.length})</h2><p className="text-sm text-amber-900">Diferenças de valor ou de situação operacional exigem conferência; frete e descontos podem explicá-las. Notas emitidas neste período podem estar ligadas a pedidos de outros dias: esses pedidos aparecem aqui, mas não entram nos totais operacionais do período. Nenhum imposto é calculado ou estado é alterado aqui.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Canal / pedido</th><th className="px-4 py-3">Nota</th><th className="px-4 py-3 text-right">Pedido</th><th className="px-4 py-3 text-right">Nota</th><th className="px-4 py-3 text-right">Diferença</th><th className="px-4 py-3">Conferir</th></tr></thead><tbody className="divide-y divide-slate-100">{report.reviewSales.length === 0 && <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-500">Nenhuma divergência identificada entre os pedidos e notas vinculados neste período.</td></tr>}{report.reviewSales.map(sale => <tr key={`${sale.channel}:${sale.externalSaleId}`}><td className="px-4 py-3"><span className="font-semibold">{channelLabel[sale.channel] || sale.channel}</span><br/><span className="font-mono text-xs">{sale.externalSaleId}</span></td><td className="px-4 py-3">{sale.document?.model === '65' ? 'NFC-e' : 'NF-e'} {sale.document?.number || 's/n'}</td><td className="px-4 py-3 text-right">{money(sale.totalCents)}</td><td className="px-4 py-3 text-right">{sale.documentTotalCents === undefined ? '—' : money(sale.documentTotalCents)}</td><td className="px-4 py-3 text-right font-semibold">{sale.amountDifferenceCents === undefined ? '—' : money(sale.amountDifferenceCents)}</td><td className="px-4 py-3 text-amber-900">{sale.reviewReasons?.map(reason => reviewLabel[reason] || reason).join('; ')}{sale.reviewReasons?.includes('sale_outside_period') && <p className="mt-1 text-xs">Pedido criado em {reportDate(sale.occurredAt)}</p>}{sale.statusCapturedAt && <p className="mt-1 text-xs">Status capturado em {new Date(sale.statusCapturedAt).toLocaleString('pt-BR')}</p>}</td></tr>)}</tbody></table></div></section>
      <section id="vendas" className="scroll-mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="font-bold text-slate-900">Vendas do período</h2><p className="text-sm text-slate-500">“Pendente de conciliação” significa que a nota ainda não foi vinculada nesta base; não confirma venda sem nota.</p></div><label className="text-sm font-semibold text-slate-700">Buscar venda<input type="search" value={saleSearch} onChange={event => { setSaleSearch(event.target.value); setVisibleSaleCount(50); }} placeholder="Pedido, canal ou situação" className="mt-1 block w-64 max-w-full rounded-lg border border-slate-300 px-3 py-2" /></label></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Canal</th><th className="px-4 py-3">Referência</th><th className="px-4 py-3">Situação fiscal</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Detalhes</th></tr></thead><tbody className="divide-y divide-slate-100">{matchingSales.length === 0 && <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Nenhuma venda encontrada para este filtro ou busca.</td></tr>}{matchingSales.slice(0, visibleSaleCount).map(sale => <tr key={`${sale.channel}:${sale.externalSaleId}`}><td className="whitespace-nowrap px-4 py-3">{reportDate(sale.occurredAt)}</td><td className="px-4 py-3">{channelLabel[sale.channel] || sale.channel}</td><td className="px-4 py-3 font-mono text-xs">{['pdv','online'].includes(sale.channel) ? formatReferenceNumber(sale.externalSaleId) : sale.externalSaleId}</td><td className="px-4 py-3">{fiscalLabel[sale.fiscalState] || sale.fiscalState}</td><td className="px-4 py-3 text-right font-semibold">{money(sale.totalCents)}</td><td className="px-4 py-3"><button type="button" aria-haspopup="dialog" onClick={() => setExpandedSale(`${sale.channel}:${sale.externalSaleId}`)} className="whitespace-nowrap rounded-lg border border-blue-200 px-3 py-2 font-semibold text-blue-700 hover:bg-blue-50">Ver detalhes</button></td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-4 text-sm text-slate-600"><span>Mostrando {Math.min(matchingSales.length, visibleSaleCount)} de {matchingSales.length} venda(s)</span>{matchingSales.length > visibleSaleCount && <button type="button" onClick={() => setVisibleSaleCount(count => count + 50)} className="rounded-lg border border-blue-200 px-3 py-2 font-semibold text-blue-700 hover:bg-blue-50">Mostrar mais 50</button>}</div></section>
      {selectedSale && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/50" onClick={() => setExpandedSale('')}><section role="dialog" aria-modal="true" aria-label={`Venda ${selectedSale.externalSaleId}`} className="flex h-full w-full max-w-3xl flex-col bg-white shadow-2xl" onClick={event => event.stopPropagation()}><header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-slate-200 bg-white p-4 sm:p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">{channelLabel[selectedSale.channel] || selectedSale.channel}</p><h2 className="break-all text-lg font-bold text-slate-900">Venda {['pdv','online'].includes(selectedSale.channel) ? formatReferenceNumber(selectedSale.externalSaleId) : selectedSale.externalSaleId}</h2><p className="text-sm text-slate-600">{reportDate(selectedSale.occurredAt)} · {money(selectedSale.totalCents)} · {fiscalLabel[selectedSale.fiscalState] || selectedSale.fiscalState}</p></div><button ref={closeSaleRef} type="button" onClick={() => setExpandedSale('')} className="shrink-0 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Fechar ×</button></header><div className="min-h-0 flex-1 overflow-y-auto"><AccountantSaleDetailsPanel companyId={report.company.id} channel={selectedSale.channel} saleId={selectedSale.externalSaleId} adminMode={adminMode} onClose={() => setExpandedSale('')} /></div></section></div>}
      <section id="notas-importadas" className="scroll-mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-bold text-slate-900">Notas fiscais cadastradas neste sistema</h2><p className="text-sm text-slate-500">Mostra apenas as notas importadas ou emitidas aqui. O canal é identificado pelo número do pedido quando há correspondência; sem vínculo único, permanece não identificado.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Emissão</th><th className="px-4 py-3">Canal</th><th className="px-4 py-3">Nota</th><th className="px-4 py-3">Pedido</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3 text-right">Valor</th><th className="px-4 py-3">Documento</th></tr></thead><tbody className="divide-y divide-slate-100">{view?.documents.length === 0 && <tr><td colSpan={7} className="px-4 py-8 text-center text-slate-500">Nenhuma nota cadastrada para este filtro e período.</td></tr>}{view?.documents.map((document, index) => <tr key={`${document.model}:${document.number || index}:${document.issuedAt}`}><td className="whitespace-nowrap px-4 py-3">{reportDate(document.issuedAt)}</td><td className="px-4 py-3">{channelLabel[document.channel] || 'Canal não identificado'}</td><td className="px-4 py-3">{document.model === '65' ? 'NFC-e' : 'NF-e'} {document.number || 's/n'}</td><td className="px-4 py-3 font-mono text-xs">{document.orderReference || '—'}</td><td className="px-4 py-3">{document.status === 'authorized' ? 'Autorizada' : 'Cancelada'}</td><td className="px-4 py-3 text-right font-semibold">{money(document.totalCents)}</td><td className="px-4 py-3"><AccountantFiscalFileActions key={`${report.company.id}:${document.id}`} companyId={report.company.id} documentId={document.id} fileAvailable={document.fileAvailable} adminMode={adminMode} /></td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5">
        <h2 className="font-bold text-slate-900">Consultar situação da NF-e na SEFAZ-PE</h2>
        <p className="mt-1 text-sm text-slate-600">Consulta de protocolo em produção com o A1 da empresa. A resposta não altera a nota importada nem a classificação do pedido.</p>
        <div className="mt-3 flex flex-wrap items-end gap-3">
          <label className="min-w-64 flex-1 text-sm font-semibold">NF-e
            <select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={selectedDocumentId} onChange={event => { setSelectedDocumentId(event.target.value); setSefazResult(null); setSefazError(''); setCancellationResult(null); setCancellationError(''); }}>
              <option value="">Selecione uma nota</option>
              {report.documents.filter(document => document.model === '55').map(document => <option key={document.id} value={document.id}>NF-e {document.number || 's/n'} · {channelLabel[document.channel] || 'Canal não identificado'} · {reportDate(document.issuedAt)}</option>)}
            </select>
          </label>
          <button type="button" onClick={() => void consultSefaz()} disabled={!selectedDocumentId || sefazBusy} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{sefazBusy ? 'Consultando…' : 'Consultar SEFAZ'}</button>
          {adminMode && <button type="button" onClick={() => void assessCancellation()} disabled={!selectedDocumentId || cancellationBusy || !report.documents.some(document => document.id === selectedDocumentId && document.model === '55' && ['shopee','tiktok'].includes(document.channel))} className="rounded-lg border border-amber-500 px-4 py-2 font-semibold text-amber-900 disabled:opacity-50">{cancellationBusy ? 'Conferindo…' : 'Conferir cancelamento'}</button>}
        </div>
        {sefazError && <p role="alert" className="mt-3 text-sm text-red-700">{sefazError}</p>}
        {sefazResult && <p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-950">SEFAZ produção: {sefazResult.cStat} — {sefazResult.reason}. Consulta em {new Date(sefazResult.checkedAt).toLocaleString('pt-BR')}. Confira qualquer divergência com o contador antes de alterar a nota.</p>}
        {cancellationError && <p role="alert" className="mt-3 text-sm text-red-700">{cancellationError}</p>}
        {cancellationResult && <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><strong>Conferência somente de leitura:</strong> pedido {cancellationResult.marketplace.status || 'sem status'} no {channelLabel[cancellationResult.channel] || cancellationResult.channel}; {cancellationResult.marketplace.shipped ? 'há sinal de envio; cancelamento automático bloqueado' : cancellationResult.marketplace.open ? 'pedido em aberto; manter alerta sem cancelar' : 'sem sinal positivo de envio na resposta atual'}. SEFAZ: {cancellationResult.sefaz.cStat} — {cancellationResult.sefaz.reason}. {cancellationResult.assessment.eligible ? 'Critérios da regra atendidos; esta conferência não enviou evento.' : `Envio bloqueado: ${cancellationResult.assessment.blockers.join(', ')}.`}</div>}
      </section>
      <FiscalDocumentReviewPanel companyId={companyId} documentId={selectedDocumentId} />
    </>}
  </section>;
}

export default function AccountantPortalPage() {
  const [tab, setTab] = useState<'validation' | 'revenue'>('validation');
  const { customer, signOut } = useVpsAuth();
  return <div className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white"><Building2 size={22}/></div><div><h1 className="font-black text-slate-900">Espaço do Contador</h1><p className="text-sm text-slate-500">Mercado do Vale · acesso contábil restrito</p></div></div><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-600 sm:inline">{customer?.name}</span><button type="button" onClick={() => void signOut()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700"><LogOut size={16}/>Sair</button></div></div></header><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6"><nav className="flex gap-2 rounded-xl border border-slate-200 bg-white p-2"><button type="button" onClick={() => setTab('validation')} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${tab === 'validation' ? 'bg-blue-600 text-white' : 'text-slate-700 hover:bg-slate-100'}`}><FileCheck2 size={17}/>Validação fiscal</button><button type="button" onClick={() => setTab('revenue')} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${tab === 'revenue' ? 'bg-blue-600 text-white' : 'text-slate-700 hover:bg-slate-100'}`}><ReceiptText size={17}/>Faturamento</button></nav>{tab === 'validation' ? <><AccountantNfceSequencePanel /><CompanyTaxValidationPanel api={accountantPortalService} /></> : <RevenuePanel />}</main></div>;
}
