import React, { useEffect, useMemo, useState } from 'react';
import { Building2, FileCheck2, LogOut, ReceiptText, RefreshCw } from 'lucide-react';
import { useVpsAuth } from '../../contexts/VpsAuthContext';
import { CompanyTaxValidationPanel } from '../../components/company/CompanyTaxValidationPanel';
import { accountantPortalService, type AccountantCompany, type AccountantRevenueReport } from '../../services/accountantPortalService';

const money = (cents: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format((Number(cents) || 0) / 100);
const reportDate = (value: string) => new Date(value).toLocaleDateString('pt-BR', { timeZone: 'UTC' });
const today = () => new Date().toISOString().slice(0, 10);
const yearStart = () => `${new Date().getFullYear()}-01-01`;
const fiscalLabel: Record<string, string> = {
  invoiced: 'Com documento autorizado', no_invoice_confirmed: 'Sem nota confirmado', reconciliation_pending: 'Pendente de conciliação',
  cancelled: 'Cancelada/estornada', operational_pending: 'Pendente operacional',
};
const channelLabel: Record<string, string> = { shopee: 'Shopee', tiktok: 'TikTok Shop', unidentified: 'Canal não identificado', pdv: 'PDV', online: 'Site' };
const reviewLabel: Record<string, string> = {
  amount_difference: 'Valor do pedido diferente da nota',
  operational_pending_with_document: 'Status capturado como pendente; conferir situação atual do pedido',
  cancelled_with_document: 'Status capturado como cancelado; conferir situação atual do pedido',
  sale_outside_period: 'Pedido criado fora do período selecionado; exibido somente para conferência',
};

function RevenuePanel() {
  const [companies, setCompanies] = useState<AccountantCompany[]>([]);
  const [companyId, setCompanyId] = useState('');
  const [from, setFrom] = useState(yearStart);
  const [to, setTo] = useState(today);
  const [report, setReport] = useState<AccountantRevenueReport | null>(null);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { accountantPortalService.list().then(result => { setCompanies(result.companies); setCompanyId(result.companies[0]?.id || ''); }).catch(err => setError(err.message)).finally(() => setBusy(false)); }, []);
  const load = async () => {
    if (!companyId) return;
    setBusy(true); setError('');
    try { setReport(await accountantPortalService.revenue(companyId, from, to)); } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao carregar faturamento.'); } finally { setBusy(false); }
  };
  useEffect(() => { if (companyId) void load(); }, [companyId]);
  const cards = useMemo(() => report ? [
    ['Vendas concluídas', report.totals.operationalCents, 'text-slate-900'],
    ['Notas autorizadas', report.documentTotals.authorizedDocumentCents, 'text-emerald-700'],
    ['Notas canceladas', report.documentTotals.cancelledDocumentCents, 'text-red-700'],
    ['Sem nota confirmado', report.totals.noInvoiceConfirmedCents, 'text-amber-700'],
    ['Pendente de conciliação', report.totals.reconciliationPendingCents, 'text-blue-700'],
  ] as const : [], [report]);
  return <section className="space-y-5">
    <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-3 md:grid-cols-4"><label className="text-sm font-semibold">Empresa<select className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={companyId} onChange={event => setCompanyId(event.target.value)}>{companies.map(company => <option key={company.id} value={company.id}>{company.name}</option>)}</select></label><label className="text-sm font-semibold">De<input type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="text-sm font-semibold">Até<input type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" value={to} onChange={event => setTo(event.target.value)} /></label><button type="button" onClick={load} disabled={busy || !companyId || from > to} className="mt-6 inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 font-semibold text-white disabled:opacity-50"><RefreshCw size={17} className={busy ? 'animate-spin' : ''}/>Atualizar</button></div></div>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    {report && <>
      {!report.coverage.available && <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{report.coverage.reason}</p>}
      {report.coverage.note && <p className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>Escopo atual:</strong> {report.coverage.note} As datas de pedidos e notas seguem o mesmo dia usado pelo filtro, sem conversão pelo fuso do navegador. Os totais de notas autorizadas e canceladas vêm dos documentos fiscais importados; a vinculação de cada nota à venda aparece separadamente na conciliação. Este relatório não calcula impostos.</p>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,color]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-2xl font-black ${color}`}>{money(value)}</p></article>)}</div>
      <section className="overflow-hidden rounded-2xl border border-amber-200 bg-white"><div className="border-b border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Pedidos e notas para conferir ({report.reviewSales.length})</h2><p className="text-sm text-amber-900">Diferenças de valor ou de situação operacional exigem conferência; frete e descontos podem explicá-las. Notas emitidas neste período podem estar ligadas a pedidos de outros dias: esses pedidos aparecem aqui, mas não entram nos totais operacionais do período. Nenhum imposto é calculado ou estado é alterado aqui.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Canal / pedido</th><th className="px-4 py-3">Nota</th><th className="px-4 py-3 text-right">Pedido</th><th className="px-4 py-3 text-right">Nota</th><th className="px-4 py-3 text-right">Diferença</th><th className="px-4 py-3">Conferir</th></tr></thead><tbody className="divide-y divide-slate-100">{report.reviewSales.length === 0 && <tr><td colSpan={6} className="px-4 py-6 text-center text-slate-500">Nenhuma divergência identificada entre os pedidos e notas vinculados neste período.</td></tr>}{report.reviewSales.map(sale => <tr key={`${sale.channel}:${sale.externalSaleId}`}><td className="px-4 py-3"><span className="font-semibold">{channelLabel[sale.channel] || sale.channel}</span><br/><span className="font-mono text-xs">{sale.externalSaleId}</span></td><td className="px-4 py-3">{sale.document?.model === '65' ? 'NFC-e' : 'NF-e'} {sale.document?.number || 's/n'}</td><td className="px-4 py-3 text-right">{money(sale.totalCents)}</td><td className="px-4 py-3 text-right">{sale.documentTotalCents === undefined ? '—' : money(sale.documentTotalCents)}</td><td className="px-4 py-3 text-right font-semibold">{sale.amountDifferenceCents === undefined ? '—' : money(sale.amountDifferenceCents)}</td><td className="px-4 py-3 text-amber-900">{sale.reviewReasons?.map(reason => reviewLabel[reason] || reason).join('; ')}{sale.reviewReasons?.includes('sale_outside_period') && <p className="mt-1 text-xs">Pedido criado em {reportDate(sale.occurredAt)}</p>}{sale.statusCapturedAt && <p className="mt-1 text-xs">Status capturado em {new Date(sale.statusCapturedAt).toLocaleString('pt-BR')}</p>}</td></tr>)}</tbody></table></div></section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-bold text-slate-900">Movimentos do período</h2><p className="text-sm text-slate-500">“Pendente de conciliação” não significa venda sem nota; indica que o XML autorizado ainda não está vinculado ao sistema.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Canal</th><th className="px-4 py-3">Referência</th><th className="px-4 py-3">Situação fiscal</th><th className="px-4 py-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-slate-100">{report.sales.length === 0 && <tr><td colSpan={5} className="px-4 py-8 text-center text-slate-500">Nenhum movimento encontrado.</td></tr>}{report.sales.map(sale => <tr key={`${sale.channel}:${sale.externalSaleId}`}><td className="whitespace-nowrap px-4 py-3">{reportDate(sale.occurredAt)}</td><td className="px-4 py-3 uppercase">{sale.channel}</td><td className="px-4 py-3 font-mono text-xs">{sale.externalSaleId}</td><td className="px-4 py-3">{fiscalLabel[sale.fiscalState] || sale.fiscalState}</td><td className="px-4 py-3 text-right font-semibold">{money(sale.totalCents)}</td></tr>)}</tbody></table></div></section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-bold text-slate-900">Notas fiscais por canal de venda</h2><p className="text-sm text-slate-500">O canal é identificado pelo número do pedido da loja na nota, quando corresponde a um pedido sincronizado da Shopee ou do TikTok. Sem correspondência única, fica pendente de identificação.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr><th className="px-4 py-3">Emissão</th><th className="px-4 py-3">Canal</th><th className="px-4 py-3">Nota</th><th className="px-4 py-3">Pedido</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-slate-100">{report.documents.length === 0 && <tr><td colSpan={6} className="px-4 py-8 text-center text-slate-500">Nenhuma nota importada neste período.</td></tr>}{report.documents.map((document, index) => <tr key={`${document.model}:${document.number || index}:${document.issuedAt}`}><td className="whitespace-nowrap px-4 py-3">{reportDate(document.issuedAt)}</td><td className="px-4 py-3">{channelLabel[document.channel] || 'Canal não identificado'}</td><td className="px-4 py-3">{document.model === '65' ? 'NFC-e' : 'NF-e'} {document.number || 's/n'}</td><td className="px-4 py-3 font-mono text-xs">{document.orderReference || '—'}</td><td className="px-4 py-3">{document.status === 'authorized' ? 'Autorizada' : 'Cancelada'}</td><td className="px-4 py-3 text-right font-semibold">{money(document.totalCents)}</td></tr>)}</tbody></table></div></section>
    </>}
  </section>;
}

export default function AccountantPortalPage() {
  const [tab, setTab] = useState<'validation' | 'revenue'>('validation');
  const { customer, signOut } = useVpsAuth();
  return <div className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white"><Building2 size={22}/></div><div><h1 className="font-black text-slate-900">Espaço do Contador</h1><p className="text-sm text-slate-500">Mercado do Vale · acesso contábil restrito</p></div></div><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-600 sm:inline">{customer?.name}</span><button type="button" onClick={() => void signOut()} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700"><LogOut size={16}/>Sair</button></div></div></header><main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6"><nav className="flex gap-2 rounded-xl border border-slate-200 bg-white p-2"><button type="button" onClick={() => setTab('validation')} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${tab === 'validation' ? 'bg-blue-600 text-white' : 'text-slate-700 hover:bg-slate-100'}`}><FileCheck2 size={17}/>Validação fiscal</button><button type="button" onClick={() => setTab('revenue')} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${tab === 'revenue' ? 'bg-blue-600 text-white' : 'text-slate-700 hover:bg-slate-100'}`}><ReceiptText size={17}/>Faturamento</button></nav>{tab === 'validation' ? <CompanyTaxValidationPanel api={accountantPortalService} /> : <RevenuePanel />}</main></div>;
}
