import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const server = readFileSync('vps_server.cjs', 'utf8');

const requiredSnippets = [
  'process.env.AUTORESPONDER_TOKEN',
  "fastify.get('/autoresponder/settings'",
  "fastify.patch('/autoresponder/settings'",
  "fastify.get('/autoresponder/rules'",
  "fastify.post('/autoresponder/rules'",
  "fastify.patch('/autoresponder/rules/:id'",
  "fastify.delete('/autoresponder/rules/:id'",
  "fastify.post('/autoresponder/rules/from-question'",
  "fastify.post('/autoresponder/upload-attachment'",
  "fastify.get('/autoresponder/tags'",
  "fastify.post('/autoresponder/tags'",
  "fastify.patch('/autoresponder/tags/:id'",
  "fastify.delete('/autoresponder/tags/:id'",
  "fastify.get('/autoresponder/blocklist'",
  "fastify.post('/autoresponder/blocklist'",
  "fastify.post('/autoresponder/blocklist/bulk'",
  "fastify.delete('/autoresponder/blocklist/:id'",
  "fastify.get('/autoresponder/conversations'",
  "fastify.post('/autoresponder/conversations/:sender/pause'",
  "fastify.post('/autoresponder/conversations/:sender/resume'",
  "fastify.post('/autoresponder/conversations/:sender/reset-counters'",
  "fastify.post('/autoresponder/conversations/:sender/tags'",
  "fastify.get('/autoresponder/unanswered'",
  "fastify.get('/autoresponder/stats'",
  "fastify.get('/autoresponder/store-status'",
  "fastify.patch('/products/:id/tags'",
  'CREATE TABLE IF NOT EXISTS autoresponder_settings',
  'CREATE TABLE IF NOT EXISTS autoresponder_rules',
  'CREATE TABLE IF NOT EXISTS autoresponder_tags',
  'CREATE TABLE IF NOT EXISTS autoresponder_logs',
  'CREATE TABLE IF NOT EXISTS autoresponder_conversations',
  'CREATE TABLE IF NOT EXISTS autoresponder_blocklist',
  "await addColumnIfMissing('products', 'tag_ids', 'JSON NULL')",
  'enabled TINYINT(1) NOT NULL DEFAULT 0',
  'function normalizeAutoresponderSender',
  'function normalizeAutoresponderText',
  'function isAutoresponderHumanRequest',
  'function isAutoresponderGreeting',
  'function formatAutoresponderReply',
  'function appendAutoresponderRuleAttachment',
  'function splitAutoresponderRulePattern',
  'function doesAutoresponderRuleMatch',
  'async function findAutoresponderRuleMatch',
  'async function applyAutoresponderRuleConversationTag',
  'function normalizeAutoresponderTagKeywordMap',
  'function findAutoresponderProductTagKeyword',
  'async function findAutoresponderProductsByTag',
  'function formatAutoresponderProductListReply',
  'function parseAutoresponderProductImages',
  'function getAutoresponderProductMainImage',
  'function getAutoresponderProductUrl',
  'function formatAutoresponderProductCaption',
  'function formatAutoresponderProductSearchReply',
  'function isAutoresponderMoreRequest',
  'function buildAutoresponderOptionsContext',
  'function normalizeAutoresponderOptionsContext',
  'async function getAutoresponderOptionsContext',
  'function getAutoresponderNumberedChoice',
  'async function getAutoresponderNumberedChoiceContext',
  'async function findAutoresponderProductById',
  'function formatAutoresponderProductDetailReply',
  'function extractAutoresponderProductSearchTokens',
  'async function findAutoresponderProductsByTokens',
  'async function getAutoresponderFallbackState',
  'function getAutoresponderFallbackReply',
  'async function logAutoresponderReply',
  'async function upsertAutoresponderSuccessConversation',
  'async function upsertAutoresponderOptionsConversation',
  'function getAutoresponderStoreStatus',
  'function isAutoresponderStoreInHumanHours',
  'async function getAutoresponderReplyCount',
  'async function touchAutoresponderConversation',
  "timeZone: 'America/Sao_Paulo'",
  'DEFAULT_AUTORESPONDER_HOURS',
  'async function isAutoresponderBlocked',
  'SELECT business_hours, holiday_overrides, local_holidays FROM company_settings LIMIT 1',
  'settings.human_message_out_of_hours',
  'settings.max_replies_per_conversation',
  'settings.max_replies_window_hours',
  'SELECT id, match_type, pattern, reply_type, reply_text, reply_tag_id, reply_search_query, attachment_url, attachment_caption, auto_apply_tag_id',
  'FROM autoresponder_rules',
  'ORDER BY priority DESC, id ASC',
  'UPDATE autoresponder_rules SET hits = hits + 1 WHERE id = ?',
  'matched_rule_id',
  "'rule_text'",
  "'rule_product_tag'",
  "'rule_product_search'",
  'matchedRule.reply_tag_id',
  'matchedRule.reply_search_query',
  'matchedRule.auto_apply_tag_id',
  'SELECT tag_ids FROM autoresponder_conversations WHERE sender = ? LIMIT 1',
  'UPDATE autoresponder_conversations SET tag_ids = ? WHERE sender = ?',
  'Anexo:',
  'JSON_CONTAINS(tag_ids, JSON_ARRAY(?))',
  'JSON_UNQUOTE(JSON_EXTRACT(images',
  'imageUrl',
  'https://www.mercadodovale.com.br/produto/',
  "'product_tag'",
  'matched_products',
  "'purchase_product_selected'",
  'last_options_at >= DATE_SUB(NOW(), INTERVAL ? MINUTE)',
  'last_options_offered',
  "'more_products'",
  'OFFSET ${safeOffset}',
  'hasMore',
  "'product_search'",
  "LOWER(COALESCE(name, '')) LIKE ?",
  "LOWER(COALESCE(sku, '')) LIKE ?",
  "LOWER(COALESCE(brand, '')) LIKE ?",
  "LOWER(COALESCE(CAST(specs AS CHAR), '')) LIKE ?",
  "'fallback'",
  'consecutive_fallbacks',
  'auto_pause_fallback_threshold',
  'auto_pause_fallback_minutes',
  "pause_reason = 'auto_fallback'",
  'matchedRuleId = null',
  'last_options_offered = ?',
  'DATE_SUB(NOW(), INTERVAL ? HOUR)',
  "console.error('[autoresponder] webhook failed:', err)",
  'Tivemos uma instabilidade no atendimento automatico',
  'SELECT pattern, pattern_type FROM autoresponder_blocklist WHERE active = 1',
  'SELECT paused_until, pause_reason FROM autoresponder_conversations WHERE sender = ? LIMIT 1',
  'DATE_ADD(NOW(), INTERVAL ? MINUTE)',
  'DELETE FROM autoresponder_rules WHERE id = ?',
  'SELECT question FROM autoresponder_logs WHERE id = ?',
  "reply_type: 'text'",
  "path.join(UPLOADS_DIR, 'autoresponder', 'attachments')",
  "return { ok: true, url",
  'DELETE FROM autoresponder_tags WHERE id = ?',
  'DELETE FROM autoresponder_blocklist WHERE id = ?',
  "intent = 'fallback'",
  'COUNT(*) AS occurrences',
  'GROUP BY question',
  'COUNT(*) AS total_messages',
  'COUNT(DISTINCT sender) AS unique_senders',
  'UPDATE products SET tag_ids = ? WHERE id = ?',
  "'human_request'",
];

for (const snippet of requiredSnippets) {
  assert.ok(server.includes(snippet), `Missing expected snippet: ${snippet}`);
}

assert.match(server, /fastify\.route\(\{\s*method: \['GET', 'POST'\],\s*url: '\/autoresponder-webhook'/, 'Webhook route must accept GET and POST');
assert.ok(!server.includes("pause_reason = 'human_request'"), 'Human handoff must not pause the conversation anymore');
assert.ok(!server.includes('mdv_ar_8a4f9c2e1b3d7f5a6e0c8b9d2a1f4e7c'), 'Token must not be hardcoded in server code');

console.log('autoresponder phase 1A-2C static checks passed');
