import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync('pages/admin/settings/MarketingPage.tsx', 'utf8');
const panel = readFileSync('pages/admin/settings/marketing/MarketingApprovalCenterPanel.tsx', 'utf8');
const service = readFileSync('services/marketingApprovalService.ts', 'utf8');
const server = readFileSync('server.js', 'utf8');
const vpsServer = readFileSync('vps_server.js', 'utf8');
const vpsServerCjs = readFileSync('vps_server.cjs', 'utf8');
const productionApi = readFileSync('services/marketingCampaignApi.cjs', 'utf8');
const migration = readFileSync('migrations/010_marketing_approval_center.sql', 'utf8');

assert.match(page, /activeTab.*approvals/);
assert.match(page, /<MarketingApprovalCenterPanel/);
assert.match(panel, /Estado atual/);
assert.match(panel, /Resumo em linguagem simples/);
assert.match(panel, /O que será preparado/);
assert.match(panel, /Impacto financeiro máximo/);
assert.match(panel, /Gasto imediato máximo/);
assert.match(panel, /Limite mensal autorizado/);
assert.match(panel, /Público amplo e local/);
assert.match(panel, /Automático pelo servidor/);
assert.match(panel, /As estruturas das campanhas permanecem pausadas/);
assert.match(panel, /Campanha \{index \+ 1\}/);
assert.match(panel, /field === 'cards'/);
assert.match(panel, /Mensagem preparada para o bot/);
assert.match(panel, /<img src=\{imageUrl\}/);
assert.doesNotMatch(panel, /JSON\.stringify\(value\)/);
assert.match(panel, /Como desfazer/);
assert.match(panel, /Confirmar aprovação/);
assert.match(panel, /persistentOutcome/);
assert.match(panel, /h-\[100dvh\] w-screen flex-col/);
assert.match(panel, /aria-modal="true"/);
assert.match(panel, /min-h-0 flex-1 space-y-4 overflow-y-auto/);
assert.match(panel, /Tentar nova aprovação/);
assert.match(panel, /Copiar diagnóstico/);
assert.match(panel, /navigator\.clipboard\.writeText/);
assert.match(panel, /preparePausedAdBundleApproval/);
assert.match(panel, /O comprovante continuará visível na tela/);
assert.match(panel, /Criativos aprovados\. O anúncio ainda não foi criado nem colocado em veiculação/);
assert.match(panel, /Anúncios completos criados e enviados para análise da Meta, mas permanecem pausados e sem gasto/);
assert.match(panel, /setFilter\('all'\)/);
assert.match(service, /\/admin\/marketing\/approvals/);
assert.match(server, /\/admin\/marketing\/approvals\/.*\/decision/);
assert.match(server, /requireAdminBearerToken/);
assert.match(server, /MARKETING_RUNNER_SECRET/);
assert.match(server, /financial_impact, success_criteria/);
assert.match(server, /DATE_ADD\(NOW\(\), INTERVAL 24 HOUR\)/);
assert.match(productionApi, /completeApprovedManualReviews/);
assert.match(productionApi, /publicationExecuted: false/);
assert.match(productionApi, /execution_mode <> 'manual'/);
assert.match(migration, /UNIQUE KEY uq_marketing_approval_idempotency/);
assert.match(migration, /CREATE TABLE IF NOT EXISTS marketing_approval_events/);
assert.match(vpsServer, /registerMarketingCampaignRoutes/);
assert.match(vpsServer, /ensureMarketingCampaignTables/);
assert.match(vpsServerCjs, /registerMarketingCampaignRoutes/);
assert.match(vpsServerCjs, /ensureMarketingCampaignTables/);
assert.match(productionApi, /\/admin\/marketing\/approvals/);
assert.match(productionApi, /\/marketing-runner\/approvals/);
assert.match(productionApi, /meta\.create_paused_campaign_bundle\.v2/);
assert.match(productionApi, /meta\.approve_campaign_creative_plan\.v1/);
assert.match(productionApi, /meta\.create_paused_whatsapp_ad_bundle\.v1/);
assert.match(productionApi, /paused-ad-bundle-approvals/);
assert.match(productionApi, /creative-plan-approvals/);
assert.match(productionApi, /Send exactly one campaign per creative approval/);
assert.match(productionApi, /meta-creatives-v2/);
assert.match(productionApi, /Aprovar criativos: /);
assert.match(productionApi, /SELECT phone FROM company_settings LIMIT 1/);
assert.match(productionApi, /SELECT id, sku, name, price_retail, stock_quantity, status, hide_from_catalog FROM products/);
assert.match(productionApi, /The selected products changed or are no longer eligible/);
assert.match(productionApi, /marketing_approval_execution_items/);
assert.match(productionApi, /OUTCOME_SALES/);
assert.match(productionApi, /status: 'PAUSED'/);
assert.match(productionApi, /is_adset_budget_sharing_enabled: 'false'/);
assert.match(productionApi, /metaSubcode/);
assert.match(productionApi, /requester cannot approve their own/);

console.log('marketing approval center contract: OK');
