import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const server = readFileSync('vps_server.js', 'utf8');
const serverCjs = readFileSync('vps_server.cjs', 'utf8');
const page = readFileSync('pages/admin/whatsapp/NovoBotPage.tsx', 'utf8');
const service = readFileSync('services/n8nBotControlService.ts', 'utf8');
const routes = readFileSync('routes/index.tsx', 'utf8');
const layout = readFileSync('layouts/AdminLayout.tsx', 'utf8');
const patch = readFileSync('tmp-tests/n8n-add-admin-client-control.cjs', 'utf8');

for (const source of [server, serverCjs]) {
  assert.match(source, /CREATE TABLE IF NOT EXISTS n8n_bot_client_controls/, 'server must create n8n bot controls table');
  assert.match(source, /fastify\.get\('\/n8n-bot\/client-control'/, 'server must expose lookup endpoint');
  assert.match(source, /fastify\.post\('\/n8n-bot\/client-control\/block'/, 'server must expose block endpoint');
  assert.match(source, /fastify\.post\('\/n8n-bot\/client-control\/reset'/, 'server must expose reset endpoint');
  assert.match(source, /CREATE TABLE IF NOT EXISTS n8n_bot_messages/, 'server must create n8n bot messages table');
  assert.match(source, /fastify\.get\('\/n8n-bot\/conversations'/, 'server must expose n8n bot conversations endpoint');
  assert.match(source, /fastify\.get\('\/n8n-bot\/messages'/, 'server must expose n8n bot messages endpoint');
  assert.match(source, /fastify\.post\('\/n8n-bot\/messages\/log'/, 'server must expose n8n bot message log endpoint');
  assert.match(source, /buildN8nBotMemorySessionKey\(remoteJid, resetCount\)/, 'server must return versioned memory session key');
}

assert.match(service, /\/n8n-bot\/client-control\/block/, 'front service must call block endpoint');
assert.match(service, /\/n8n-bot\/client-control\/reset/, 'front service must call reset endpoint');
assert.match(service, /\/n8n-bot\/conversations/, 'front service must list n8n conversations');
assert.match(service, /\/n8n-bot\/messages/, 'front service must list n8n messages');
assert.match(page, /Bloquear fluxo/, 'new bot page must expose block action');
assert.match(page, /Limpar atendimento/, 'new bot page must expose admin reset action');
assert.match(page, /Ao vivo/, 'new bot page must expose live refresh mode');
assert.match(page, /messageTone/, 'new bot page must render a message timeline');
assert.match(routes, /NovoBotPage/, 'routes must include new bot page');
assert.match(routes, /\/admin\/whatsapp\/novo-bot/, 'routes must expose separated new bot path');
assert.match(layout, /Novo Bot/, 'admin menu must include Novo Bot');

assert.match(patch, /Controle Bot - Verificar Cliente/, 'n8n patch must add client control node');
assert.match(patch, /Controle Bot - Bloqueado\?/, 'n8n patch must add blocked IF node');
assert.match(patch, /memorySessionKey/, 'n8n patch must use versioned memory session key');
assert.match(patch, /SYNC_SECRET/, 'n8n patch must provide sync secret to workflow runtime');
assert.match(patch, /delete staticData\.salesPostList\[remoteJid\]/, 'n8n reset must clear post-list state');
assert.match(patch, /Controle Bot - Registrar Entrada/, 'n8n patch must add inbound message logger');
assert.match(patch, /Controle Bot - Buscar Controle/, 'n8n patch must use HTTP node for client control lookup');
assert.match(patch, /Controle Bot - Aplicar Controle/, 'n8n patch must restore source data after control lookup');
assert.match(patch, /Controle Bot - Reset pendente\?/, 'n8n patch must consume admin resets after applying them');
assert.match(patch, /Controle Bot - Registrar Saida/, 'n8n patch must add outbound message logger');
assert.match(patch, /Controle Bot - Restaurar Saida/, 'n8n patch must restore outbound items after logging');
assert.match(patch, /\/n8n-bot\/messages\/log/, 'n8n patch must log messages to VPS');
assert.match(patch, /n8n-nodes-base\.httpRequest/, 'n8n log/control calls must use HTTP Request nodes');
assert.match(patch, /patchTransientHttpNode/, 'n8n patch must make transient HTTP nodes resilient');
assert.match(patch, /Vendas - Buscar Taxas/, 'n8n patch must protect payment fees lookup');
assert.match(patch, /Vendas - Buscar Produtos/, 'n8n patch must protect product lookup');
assert.match(patch, /continueRegularOutput/, 'n8n HTTP failures must not abort the sales flow');
assert.match(patch, /maxTries = 3/, 'n8n transient HTTP nodes must retry before continuing');
assert.match(patch, /Enviar WhatsApp - Tipo imagem\?/, 'outbound logger must preserve the image/text router');
assert.match(patch, /Enviar WhatsApp - Imagem/, 'image messages must route to the media send node');
assert.match(patch, /imageTrueTarget/, 'patch result must report image true routing');
assert.match(patch, /imageFalseTarget/, 'patch result must report image false routing');
assert.match(patch, /Me confirma o numero do item ou o modelo/, 'photo requests without active state must ask for selection instead of reopening the catalog');
assert.match(patch, /uniqueColorItems/, 'post-list color choices must dedupe repeated stock variations');
assert.match(patch, /optionColorItems\.length === 1/, 'single unique color must be selected even when stock has duplicate rows');
assert.match(patch, /optionColorItems\.find/, 'mentioned color must resolve against deduped color options');
assert.match(patch, /quantityIntent/, 'post-list quantity step must classify full message before consuming a number');
assert.match(patch, /!wantsPhoto && quantityIntent/, 'photo requests with numbers must not be consumed as quantity');
assert.match(patch, /produto\|item\|do\|da/, 'post-list selection must understand contextual number references like foto do 22');
assert.match(patch, /Vendas - Preparar Contexto IA/, 'sales flow must prepare state context before the classifier');
assert.match(patch, /salesConversationState/, 'classifier must receive the active sales state');
assert.match(patch, /Agente Inicial e Roteador/, 'initial AI agent must own routing and flow intent decisions');
assert.match(patch, /fluxo_venda/, 'classifier JSON must include sales flow action');
assert.match(patch, /salesFlowAction/, 'post-list executor must consume AI flow action');
assert.match(patch, /aiAction === 'informar_quantidade'/, 'quantity must come from AI-classified intent before fallback parsing');
assert.match(patch, /aiAction === 'nova_busca'/, 'customer can start a new search even with active sales state');
assert.match(patch, /Parse Classificacao[\s\S]*Vendas - Verificar Pos Lista/, 'post-list executor must run after AI classification');
assert.match(patch, /withGreeting/, 'post-list executor must preserve detected greetings in operational replies');
assert.match(patch, /periodGreeting/, 'post-list media replies must be able to send greeting before photos');
assert.match(patch, /No link tem mais fotos, video e as caracteristicas dele/, 'photo replies must include product link for complete media and characteristics');
assert.match(patch, /slice\(0, 3\)/, 'photo replies should send a small WhatsApp preview instead of flooding all media');
assert.match(patch, /nextCode = nextCode\.replace\([\s\S]*titleCase\(item\.color\)[\s\S]*,\s*''\s*\)/, 'photo replies must remove the standalone color text because the caption already includes it');
assert.match(patch, /buildAllPhotoMessages/, 'photo requests for multi-color products must send previews instead of asking color first');
assert.match(patch, /if \(!variant && \(wantsPhoto \|\| wantsPhotoFromAI\)\)/, 'photo intent must bypass the color-question branch when no color was chosen');
assert.match(patch, /Gostou de alguma dessas cores\? Posso separar para voce/, 'multi-color photo preview must continue the sale after showing variations');

console.log('n8n admin client control static checks passed');
