import assert from 'node:assert/strict';
import { build, preview } from 'vite';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import react from '@vitejs/plugin-react';
import { chromium } from 'playwright';
const outDir = mkdtempSync(join(tmpdir(), 'mdv-pdv-payment-'));
await build({ configFile: false, envPrefix: 'PDV_TEST_ONLY_', plugins: [react()], logLevel: 'error', build: { outDir, rolldownOptions: { input: resolve('tmp-tests/pdv-payment-preview.html') } } });
const server = await preview({ configFile: false, build: { outDir }, preview: { host: '127.0.0.1', port: 3017, strictPort: true } });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
try {
    const page = await browser.newPage({ viewport: { width: 1000, height: 1000 } });
    await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:3017/') ? route.continue() : route.abort());
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const open = () => page.goto('http://127.0.0.1:3017/tmp-tests/pdv-payment-preview.html');
    await open();
    await page.getByLabel('2. Dinheiro entregue pelo cliente').fill('1.500,00');
    await page.getByRole('button', { name: 'Adicionar pagamento', exact: true }).click();
    await page.getByRole('button', { name: 'Simular salvamento' }).click();
    let saved = JSON.parse(await page.getByTestId('saved').textContent());
    assert.equal(saved.total, 100000);
    assert.equal(saved.payments[0].total_with_fee, 100000);
    assert.equal(saved.payments[0].change_amount, 50000);
    await open();
    await page.getByLabel('2. Dinheiro entregue pelo cliente').fill('100,00');
    await page.getByLabel('2. Dinheiro entregue pelo cliente').press('Enter');
    await page.waitForFunction(() => document.querySelector('input[aria-label="2. Dinheiro entregue pelo cliente"]')?.value === '900,00');
    await open();
    await page.getByRole('button', { name: 'Crédito', exact: true }).click();
    await page.getByLabel('2. Valor nesta forma de pagamento').fill('400,00');
    await page.getByRole('button', { name: /^10x/ }).click();
    assert.match(await page.locator('body').innerText(), /600,00/);
    await page.getByRole('button', { name: 'Pix', exact: true }).click();
    await page.getByLabel('Registrar Pix já recebido (conferência manual)').check();
    await page.getByRole('button', { name: 'Adicionar pagamento', exact: true }).click();
    await page.getByText('Ajustar total final da venda', { exact: true }).click();
    await page.getByLabel('Total final da venda', { exact: true }).fill('1.020,00');
    await page.getByRole('button', { name: 'Aplicar ajuste' }).click();
    await page.getByRole('button', { name: 'Simular salvamento' }).click();
    saved = JSON.parse(await page.getByTestId('saved').textContent());
    assert.equal(saved.total, 102000);
    assert.equal(saved.payments[0].total_with_fee, 42000);
    assert.equal(saved.payments[1].total_with_fee, 60000);
    await page.screenshot({ path: 'tmp-tests/pdv-payment-desktop.png', fullPage: true });
    await open();
    await page.getByRole('button', { name: 'Crediário', exact: true }).click();
    await page.getByRole('button', { name: 'Definir parcelas do crediário' }).click();
    await page.getByRole('button', { name: 'Confirmar Venda a Prazo' }).click();
    await page.getByRole('button', { name: 'Simular salvamento' }).click();
    saved = JSON.parse(await page.getByTestId('saved').textContent());
    assert.equal(saved.payments[0].method, 'a_prazo');
    assert.match(await page.locator('body').innerText(), /A receber no crediário/);
    await open();
    await page.getByRole('button', { name: 'Pix', exact: true }).click();
    await page.getByRole('button', { name: 'Gerar Pix Mercado Pago' }).click();
    await page.getByText('Aguardando pagamento', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Atualizar pagamento' }).click();
    await page.getByText('Pix aprovado automaticamente').waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    await open();
    await page.getByRole('button', { name: 'Crédito', exact: true }).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile must not overflow');
    await page.screenshot({ path: 'tmp-tests/pdv-payment-mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PDV browser: cash, split credit/Pix, adjustment, debt, Pix approval and mobile layout passed');
} finally { await browser.close(); await new Promise(resolve => server.httpServer.close(resolve)); }
