import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const page = await readFile(new URL('../pages/admin/settings/MarketingPage.tsx', import.meta.url), 'utf8');
const card = await readFile(new URL('../pages/admin/settings/marketing/ProductMarketingCard.tsx', import.meta.url), 'utf8');
const resolver = await readFile(new URL('../pages/admin/settings/marketing/productMarketingArtwork.ts', import.meta.url), 'utf8');
const commercialCopy = await readFile(new URL('../pages/admin/settings/marketing/productCommercialCopy.ts', import.meta.url), 'utf8');
const carousel = await readFile(new URL('../utils/marketing-carousel.ts', import.meta.url), 'utf8');

assert.match(page, /<ProductMarketingCard/);
assert.match(page, /useState<MarketingAssetFormat>\('status'\)/);
assert.match(page, /Gerador de Artes/);
assert.match(page, /META SEM PREÇO/);
assert.match(page, /productArtworkTemplate/);
assert.match(page, /useState<ProductMarketingTemplate>\('showcase'\)/);
assert.match(page, /Modo comercial padronizado/);
assert.match(page, /Escala das fontes/);
assert.match(page, /Opacidade do fundo/);
assert.match(page, /typographyScale=\{artworkTypographyScale \/ 100\}/);
assert.match(page, /backgroundOverlayOpacity=\{sceneOverlayOpacity \/ 100\}/);
assert.match(page, /Escala individual dos textos/);
assert.match(page, /Escala da imagem do produto/);
assert.match(page, /Ícones dos benefícios/);
assert.match(page, /typographyScales=\{artworkTypographyScales\}/);
assert.match(page, /productImageScale=\{productImageScale \/ 100\}/);
assert.match(page, /const artworkLogo = \(settings as typeof settings & \{ logo_url\?: string \}\)\.logo_url\s*\|\| companyInfo\?\.logoUrl/s);
assert.match(page, /Técnico \/ legado/);
assert.match(page, /template=\{productArtworkTemplate\}/);
assert.match(page, /selectionClearedRef/);
assert.match(page, /setCommercialCopyDraft\(null\)/);
assert.match(page, /setExportImageOverride\(undefined\)/);
assert.match(page, /if \(e\.target\.checked\).*setSelectedProduct\(p\)/s);
assert.match(page, /Textos do criativo/);
assert.match(page, /Gatilhos comerciais/);
assert.match(page, /Use até cinco/);
assert.match(page, /Gerar novamente/);
assert.match(page, /supportedBenefits/);
assert.match(page, /effectiveShowArtworkPrice/);
assert.match(page, /Foto\/variante principal da arte/);
assert.match(page, /marketing_primary_variants/);
assert.match(page, /paymentFeesService\.list\(\)/);
assert.match(page, /Confira o preço antes de baixar/);
assert.match(page, /pixDiscountPercentage/);
assert.match(page, /modelColorImagesService\.getByModelIds/);
assert.match(page, /row\.model_id === product\.model_id && row\.color_id === colorId/);
assert.match(page, /Cadastre uma foto para este modelo e esta cor na galeria/);
assert.doesNotMatch(page, /getModelImageWithCache/);
assert.match(page, /saveMarketingArtworkForWhatsappStatus/);
assert.match(page, /\/synology\/upload\?folder=imagens/);
assert.match(page, /\[targetField\]:\s*versionedUrl/);
assert.match(page, /targetField = showPrice \? 'marketing_background_url' : 'marketing_background_no_price_url'/);
assert.match(page, /format === 'status'/);
assert.match(page, /salva automaticamente como foto de marketing do Status/);
assert.doesNotMatch(page, /const productBackground = selectedProduct\?\.marketing_background_url/);

assert.match(card, /CONSULTE CORES DISPONÍVEIS/);
assert.match(card, /Total a prazo:/);
assert.match(card, /useProductCutout/);
assert.match(card, /mercado-do-vale-logo\.png/);
assert.match(card, /Consulte condições e disponibilidade/);
assert.match(card, /ProductMarketingTemplate = 'technical' \| 'showcase'/);
assert.match(card, /ProductMarketingShowcase/);
assert.match(card, /data-marketing-brand-logo/);
assert.match(card, /data-marketing-sales-triggers/);
assert.match(card, /visibleBenefits/);
assert.match(card, /slice\(0, 5\)/);
assert.match(card, /backgroundOverlayOpacity/);
assert.match(card, /typographyScales/);
assert.match(card, /productImageScale/);
assert.match(card, /BenefitIcon/);
assert.match(card, /max-h-\[520px\] max-w-\[84%\]/);
assert.match(card, /fontScale = Math\.max\(0\.85, Math\.min\(1\.2, typographyScale\)\)/);
assert.match(card, /data-marketing-scenario/);
assert.match(card, /network-rack/);
assert.match(card, /PEÇA AGORA NO WHATSAPP/);
assert.match(card, /border-r.*border-white\/20/);
assert.doesNotMatch(card, /CELULARES E ACESSÓRIOS/i);

assert.match(resolver, /calculateInstallmentFromFees\(retailPrice, paymentFees, 12\)/);
assert.match(resolver, /calculatePixPrice\(retailPrice, pixDiscountPercentage\)/);
assert.match(resolver, /cam_principal_mpx/);
assert.match(resolver, /battery_mah/);
assert.match(resolver, /identity\.includes\('poco'\)/);
assert.match(resolver, /identity\.includes\('redmi'\)/);
assert.match(resolver, /normalizeBrazilianWhatsapp/);
assert.match(resolver, /resolveSellingBadge/);
assert.match(resolver, /categoryName: clean\(categoryName\)/);
assert.match(resolver, /IDEAL PARA SUA INSTALAÇÃO/);
assert.match(resolver, /CONEXÃO ORGANIZADA/);
assert.match(card, /data\.commercial\.title/);
assert.match(card, /data\.commercial\.benefits/);
assert.match(card, /data\.commercial\.cta/);
assert.match(card, /formatProductMarketingPrice/);
assert.match(commercialCopy, /COMMERCIAL_COPY_LIMITS/);
assert.match(commercialCopy, /alegação sem apoio nos dados oficiais/);
assert.doesNotMatch(commercialCopy, /qualidade garantida/i);
assert.match(resolver, /const INTERNAL_UUID_PATTERN = \/\^\[0-9a-f\]/, 'a arte deve reconhecer e bloquear UUID interno');
assert.match(resolver, /for \(const alias of \['version', 'versão', 'versao'\]\)/, 'a versão semântica deve ter prioridade sobre o alias legado');
assert.match(resolver, /value && !INTERNAL_UUID_PATTERN\.test\(value\)/, 'UUID não pode ser exibido como versão');
assert.doesNotMatch(resolver, /const sku = clean\(product\.sku\)/, 'SKU também é identificador e não deve aparecer como versão');
assert.doesNotMatch(resolver, /readSpec\(product, \['versao', 'version', 'versão'\]\)/, 'o alias legado com UUID não deve continuar tendo prioridade');

assert.match(carousel, /imageUrl:\s*usableImages\[0\]\s*\?\?\s*null/);
assert.match(carousel, /slideNumber:\s*1/);
assert.match(carousel, /totalSlides:\s*1/);
assert.doesNotMatch(carousel, /usableImages\.map\(/);

console.log('product-marketing-artwork-static.test.mjs: ok');
