import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync('pages/admin/settings/ShopeePage.tsx', 'utf8');
const api = readFileSync('api/shopee-catalog.ts', 'utf8');
const docs = readFileSync('Shopee.md', 'utf8');

assert.match(page, /shopeeVariationEngine/, 'Shopee page should import the variation engine');
assert.match(page, /variationGroups/, 'Shopee page should discover selectable variation groups');
assert.match(page, /selectedVariationGroupId/, 'Shopee modal should track the selected variation group');
assert.match(page, /buildShopeeVariationModels/, 'publish flow should build tier_variation and model_list');
assert.match(page, /tier_variation/, 'add_item payload should include Shopee tier variations');
assert.match(page, /model_list/, 'add_item payload should include Shopee model list');
assert.match(page, /Publicar como anuncio com variacoes/, 'operator should explicitly opt in to variation publish');
assert.match(page, /setPublishWithVariations\(true\)/, 'matching variation groups should auto-enable variation publish');
assert.match(page, /setPublishWithVariations\(false\)/, 'products without a matching variation group should keep variation publish off');
assert.match(page, /setSelectedVariationGroupId\(''\)/, 'products without a matching variation group should clear variation group selection');
assert.match(page, /Selecione grupo/, 'variation status should be neutral when no group is selected');
assert.doesNotMatch(page, /missingSupabaseProducts|supaProds|supaMap/, 'Shopee page should not use Supabase as a catalog fallback for variation groups');
assert.match(page, /getProductsByParentId/, 'Shopee modal should fetch missing variation siblings from VPS');
assert.doesNotMatch(page, /seller_stock:\s*undefined/, 'variation add_item payload must not send a null seller_stock field');
assert.match(page, /postShopeeDebug\('add_item',\s*variationPayload,\s*'add_item:variation'\)/, 'variation add_item should first send variation payload directly');
assert.match(page, /publishShopeeVariationItem\(basePayload,\s*finalPayload,\s*\{[\s\S]*model_list: variationModelListForPublish,[\s\S]*\},\s*parsedStock\)/, 'variation add_item should use the variation publish fallback wrapper with prepared model list');
assert.doesNotMatch(page, /publishShopeeItemWithStockFallback\(finalPayload, variationTotalStock\)/, 'variation add_item must not add simple-item stock fallback fields');
assert.match(page, /variation_image:skipped/, 'variation image download failures should be logged as skipped instead of aborting publish');
assert.match(page, /continue;/, 'variation image download failures should continue publishing without optional option image');
assert.match(page, /variation_image:missing/, 'variation publish should log which option product has no usable image');
assert.match(page, /variation_image:coverage/, 'variation publish should log option image coverage before building Shopee models');
assert.doesNotMatch(page, /const firstImage = Array\.isArray\(child\.images\) \? child\.images\[0\]/, 'variation image upload should not only inspect the first image slot');
assert.match(page, /variationProductIds=\{bulkQueueIds\}/, 'bulk variation publish should scope models to the selected bulk queue');
assert.match(page, /rawSelectedVariationGroup/, 'Shopee modal should keep the raw group separate from the publish-scoped group');
assert.match(page, /rawSelectedVariationGroup\.children\.filter\(\(child\) => allowedIds\.has\(child\.id\)\)/, 'variation publish should exclude unselected group children from model_list');
assert.match(page, /findExistingShopeeItemForDuplicate/, 'variation fallback should recover from duplicate base items');
assert.match(page, /duplicate_lookup:match/, 'duplicate recovery should log the reused Shopee item');
assert.match(page, /add_item:variation_fallback_duplicate_reused/, 'variation fallback should reuse duplicate items before init_tier_variation');
assert.match(page, /isShopeeVideoDispatcherError/, 'add_item should detect Shopee MMS video dispatcher failures');
assert.match(page, /add_item:video_dispatcher_retry_without_video/, 'add_item should retry without video when Shopee MMS validation times out');
assert.match(page, /delete retryPayload\.video_upload_id/, 'video dispatcher retry should remove video_upload_id from add_item payload');
assert.match(page, /omitted_video_upload_id/, 'post-publish video attach should know when video was intentionally omitted');
assert.match(page, /video_precheck:existing_item/, 'variation publish should inspect existing Shopee item video before uploading');
assert.match(page, /upload_video:skipped_existing_video/, 'variation publish should skip video upload when Shopee item already has video');
assert.match(page, /videoAlreadyPresentOnShopee/, 'post-publish verification should account for videos already saved on Shopee');
assert.match(page, /init_tier_variation/, 'seller_stock-constrained variation add_item should initialize variations after base item fallback');
assert.match(page, /add_item:variation_fallback_base/, 'variation fallback should log base item creation before initializing variations');
assert.match(api, /action === 'init_tier_variation'/, 'API must expose init_tier_variation action');
assert.match(api, /\/api\/v2\/product\/init_tier_variation/, 'API must call Shopee init_tier_variation endpoint');
assert.match(docs, /Primeira entrega: variacoes manuais/, 'Shopee docs should document the first manual variation delivery');

console.log('shopee variation modal static checks passed');
