import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync('pages/admin/settings/ShopeePage.tsx', 'utf8');
const api = readFileSync('api/shopee-catalog.ts', 'utf8');
const docs = readFileSync('Shopee.md', 'utf8');
const vpsService = readFileSync('services/vpsApiService.ts', 'utf8');
const vpsServer = readFileSync('vps_server.cjs', 'utf8');
const vpsServerJs = readFileSync('vps_server.js', 'utf8');

assert.match(page, /shopeeVariationEngine/, 'Shopee page should import the variation engine');
assert.match(page, /variationGroups/, 'Shopee page should discover selectable variation groups');
assert.match(page, /selectedVariationGroupId/, 'Shopee modal should track the selected variation group');
assert.match(page, /buildShopeeVariationModels/, 'publish flow should build tier_variation and model_list');
assert.match(page, /buildShopeeUpdateStockPayload/, 'simple item publish/update should build an explicit update_stock payload');
assert.match(page, /tier_variation/, 'add_item payload should include Shopee tier variations');
assert.match(page, /model_list/, 'add_item payload should include Shopee model list');
assert.match(page, /Publicar como anuncio com variacoes/, 'operator should explicitly opt in to variation publish');
assert.match(page, /setPublishWithVariations\(true\)/, 'matching variation groups should auto-enable variation publish');
assert.match(page, /setPublishWithVariations\(false\)/, 'products without a matching variation group should keep variation publish off');
assert.match(page, /setSelectedVariationGroupId\(''\)/, 'products without a matching variation group should clear variation group selection');
assert.match(page, /Selecione grupo/, 'variation status should be neutral when no group is selected');
assert.match(page, /reloadShopeeTemplates/, 'Shopee modal should expose a reusable template reload function');
assert.match(page, /shopee_templates_updated/, 'Shopee modal should listen for template updates from the templates tab');
assert.match(page, /document\.visibilityState === 'visible'/, 'Shopee modal should refresh templates when the tab becomes visible again');
assert.match(page, /Criar grupo de variacoes/, 'UI must let the operator create a missing variation group');
assert.match(page, /suggestShopeeVariationGroupByName/, 'Shopee modal must suggest missing groups from matching product names');
assert.match(page, /persistSuggestedVariationGroup/, 'Shopee modal must persist newly created groups in the VPS');
assert.match(page, /updateProductVariationGroup\(\s*suggestedVariationGroup\.parent\.id/, 'new variation groups must be saved through VPS parent_id');
assert.match(vpsService, /\/products\/variation-group/, 'VPS service must call the variation-group endpoint');
assert.match(vpsServer, /fastify\.patch\('\/products\/variation-group'/, 'VPS must expose a focused variation-group endpoint');
assert.match(vpsServer, /UPDATE products SET parent_id=\?/, 'VPS variation endpoint must persist child parent_id without full product overwrite');
assert.match(vpsServerJs, /fastify\.patch\('\/products\/variation-group'/, 'deployed VPS server file must expose the variation-group endpoint');
assert.doesNotMatch(page, /missingSupabaseProducts|supaProds|supaMap/, 'Shopee page should not use Supabase as a catalog fallback for variation groups');
assert.match(page, /getProductsByParentId/, 'Shopee modal should fetch missing variation siblings from VPS');
assert.doesNotMatch(page, /seller_stock:\s*undefined/, 'variation add_item payload must not send a null seller_stock field');
assert.match(page, /postShopeeDebugWithRetry\('add_item',\s*variationPayload,\s*'add_item:variation',[\s\S]*shouldRetry:\s*\(error\)\s*=>\s*isShopeeGtinValidationRateLimitError\(error\?\.message\s*\|\|\s*error\)/, 'variation add_item should retry transient Shopee GTIN rate limits');
assert.match(page, /postShopeeDebugWithRetry\('add_item',\s*payload,\s*`add_item:\$\{variant\.key\}`,[\s\S]*shouldRetry:\s*\(error\)\s*=>\s*isShopeeGtinValidationRateLimitError\(error\?\.message\s*\|\|\s*error\)/, 'simple add_item should retry transient Shopee GTIN rate limits');
assert.match(page, /postShopeeDebug\('update_stock',\s*stockPayload,\s*'post_publish:update_stock'\)/, 'simple item publish/update must explicitly sync stock after Shopee accepts the item');
assert.match(page, /postShopeeDebugWithRetry\('add_item',\s*retryPayload,\s*`add_item:\$\{variant\.key\}:without_video`,[\s\S]*shouldRetry:\s*\(error\)\s*=>\s*isShopeeGtinValidationRateLimitError\(error\?\.message\s*\|\|\s*error\)/, 'video fallback add_item should also retry transient Shopee GTIN rate limits');
assert.match(page, /isShopeeAttributeValidationError/, 'add_item should detect Shopee category attribute validation failures');
assert.match(page, /add_item:attribute_retry_without_optional_custom_values/, 'add_item should retry without optional custom-value attributes after Shopee attribute validation failures');
assert.match(page, /publishShopeeVariationItem\(basePayload,\s*finalPayload,\s*\{[\s\S]*model_list: variationModelListForPublish,[\s\S]*\},\s*parsedStock\)/, 'variation add_item should use the variation publish fallback wrapper with prepared model list');
assert.doesNotMatch(page, /publishShopeeItemWithStockFallback\(finalPayload, variationTotalStock\)/, 'variation add_item must not add simple-item stock fallback fields');
assert.match(page, /variation_image:skipped/, 'variation image download failures should be logged as skipped instead of aborting publish');
assert.match(page, /continue;/, 'variation image download failures should continue publishing without optional option image');
assert.match(page, /variation_image:missing/, 'variation publish should log which option product has no usable image');
assert.match(page, /variation_image:coverage/, 'variation publish should log option image coverage before building Shopee models');
assert.doesNotMatch(page, /const firstImage = Array\.isArray\(child\.images\) \? child\.images\[0\]/, 'variation image upload should not only inspect the first image slot');
assert.match(page, /rawSelectedVariationGroup/, 'Shopee modal should keep the raw group separate from the publish-scoped group');
assert.doesNotMatch(page, /rawSelectedVariationGroup\.children\.filter\(\(child\) => allowedIds\.has\(child\.id\)\)/, 'bulk variation publish must not drop siblings outside the current bulk queue');
assert.match(page, /onSuccess\(syncedProductIds\)/, 'variation publish should report all synced product ids to the bulk runner');
assert.match(page, /publishedProductIds/, 'bulk runner should advance all product ids synced by a variation publish');
assert.match(page, /findExistingShopeeItemForDuplicate/, 'variation fallback should recover from duplicate base items');
assert.match(page, /duplicate_lookup:match/, 'duplicate recovery should log the reused Shopee item');
assert.match(page, /add_item:variation_fallback_duplicate_reused/, 'variation fallback should reuse duplicate items before init_tier_variation');
assert.match(page, /proactiveDuplicateItem[\s\S]*findExistingShopeeItemForDuplicate\(\{[\s\S]*item_sku: cleanItemSku/, 'publish flow should proactively look up an existing Shopee item before add_item can create a duplicate');
assert.match(page, /existing_variation_item_id_source/, 'variation publish should log whether it reused local or remote duplicate linkage');
assert.match(page, /handleDeleteShopeeProductAndLink/, 'Shopee page should expose a focused delete-and-unlink action for bad Shopee items');
assert.match(page, /action=delete_item[\s\S]*item_id:\s*p\.shopee_item_id/, 'delete action should remove the selected item from Shopee before unlinking locally');
assert.match(page, /from\('shopee_products'\)[\s\S]*\.delete\(\)[\s\S]*\.eq\('shopee_item_id',\s*p\.shopee_item_id\)/, 'delete action should delete only local link rows for the selected Shopee item id');
assert.match(page, /Apagar da Shopee e excluir vinculo/, 'linked products should show a delete-and-unlink button for operators');
assert.match(page, /fetchAllVpsProducts[\s\S]*pageSize\s*=\s*2000[\s\S]*offset/, 'Shopee product list should page through the VPS 2000-item cap');
assert.doesNotMatch(page, /getProducts\(\{\s*limit:\s*5000/, 'Shopee product list should not rely on a single VPS request above the server cap');
assert.match(page, /isShopeeVideoDispatcherError/, 'add_item should detect Shopee MMS video dispatcher failures');
assert.match(page, /add_item:video_dispatcher_retry_without_video/, 'add_item should retry without video when Shopee MMS validation times out');
assert.match(page, /delete retryPayload\.video_upload_id/, 'video dispatcher retry should remove video_upload_id from add_item payload');
assert.match(page, /omitted_video_upload_id/, 'post-publish video attach should know when video was intentionally omitted');
assert.match(page, /video_precheck:existing_item/, 'variation publish should inspect existing Shopee item video before uploading');
assert.match(page, /upload_video:skipped_existing_video/, 'variation publish should skip video upload when Shopee item already has video');
assert.match(page, /videoAlreadyPresentOnShopee/, 'post-publish verification should account for videos already saved on Shopee');
assert.match(page, /init_tier_variation/, 'seller_stock-constrained variation add_item should initialize variations after base item fallback');
assert.match(page, /add_item:variation_fallback_base/, 'variation fallback should log base item creation before initializing variations');
assert.match(page, /isShopeeGtinValidationRateLimitError/, 'variation init should detect Shopee GTIN validation rate limits');
assert.match(page, /postShopeeDebugWithRetry\('init_tier_variation'/, 'variation init should retry transient Shopee GTIN rate limits');
assert.match(page, /debugLabel\}:retry/, 'variation init retry attempts should be logged');
assert.match(api, /action === 'init_tier_variation'/, 'API must expose init_tier_variation action');
assert.match(api, /\/api\/v2\/product\/init_tier_variation/, 'API must call Shopee init_tier_variation endpoint');
assert.match(api, /action === 'delete_item'/, 'API must expose delete_item action');
assert.match(api, /\/api\/v2\/product\/delete_item/, 'API must call Shopee delete_item endpoint');
assert.match(docs, /Primeira entrega: variacoes manuais/, 'Shopee docs should document the first manual variation delivery');

console.log('shopee variation modal static checks passed');
