import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync('pages/admin/settings/TikTokShopPage.tsx', 'utf8');
const bulk = readFileSync('pages/admin/settings/components/TikTokShopBulkPreparation.tsx', 'utf8');
const vpsServer = readFileSync('vps_server.cjs', 'utf8');

assert.match(page, /TikTokShopBulkPreparation/, 'TikTok page must mount the bulk screen');
assert.match(bulk, /Envio em massa/, 'bulk screen must be visible');
assert.match(bulk, /Diagnostico/, 'bulk screen must show diagnostics');
assert.match(bulk, /Criar rascunhos/, 'bulk screen must expose draft creation');
assert.match(bulk, /Publicar rascunhos/, 'bulk screen must expose draft publishing');
assert.match(bulk, /Reenviar rascunhos/, 'bulk screen must expose resending');
assert.match(bulk, /Atualizar anuncios/, 'bulk screen must expose updates');
assert.match(bulk, /getProductLinks/, 'bulk screen must load TikTok links');
assert.match(bulk, /publishDraft/, 'bulk screen must use the real publish endpoint');
assert.match(bulk, /startDraftJob/, 'bulk screen must create every selected draft through the queue');
assert.match(bulk, /setLinks\(\(current\)[\s\S]*tiktok_product_id/, 'completed draft jobs must refresh their TikTok link before publishing');
assert.match(bulk, /Buscar por nome, SKU, categoria ou marca/, 'bulk screen must offer text filtering');
assert.match(bulk, /Selecionar prontos filtrados/, 'bulk screen must select all eligible filtered products');
assert.match(bulk, /useState\('positive'\)/, 'bulk screen must default to products with stock');
assert.match(bulk, /useState\('NOT_SENT'\)/, 'bulk screen must default to products not yet sent');
assert.match(bulk, /Atualizar/, 'bulk screen must expose update state for sent products');
assert.match(bulk, /titleNeedsCompatibilityWording/, 'bulk screen must identify titles that need compatibility wording');
assert.match(bulk, /Titulo ajustado/, 'bulk screen must show when a title will be corrected');
assert.match(bulk, /ref=\{progressRef\}/, 'bulk screen must anchor automatic progress scrolling');
assert.match(bulk, /scrollIntoView/, 'bulk screen must scroll to progress after sending');
assert.match(bulk, /bg-emerald-50/, 'completed drafts must have a distinct success state');
assert.match(bulk, /Lista de correcoes/, 'bulk screen must show a correction queue for failed items');
assert.match(bulk, /Corrigir anuncio/, 'bulk screen must link failed items to the correction flow');
assert.match(bulk, /setCorrections/, 'failed draft jobs must block the product until corrected');
assert.match(bulk, /!variationGroups\.parentIdByChild\.has\(product\.id\)/, 'A selected child must not be sent separately from its parent');
assert.match(bulk, /groupChildren\.some\(hasProductImage\)/, 'A parent must be eligible when one of its variations has an image');
assert.match(vpsServer, /function cleanTikTokDraftTitleVps/, 'API must normalize the TikTok draft title');
assert.match(vpsServer, /replace\(\/\\bpara\\b\/gi, 'Compatível com'\)/, 'API must use compatibility wording in TikTok titles');
assert.match(vpsServer, /cleanTikTokDraftTitleVps\(product\.name\)/, 'TikTok draft creation must use the normalized title');
assert.match(vpsServer, /probeTikTokDraftVideoUrlVps/, 'TikTok drafts must validate configured videos before downloading them');
assert.match(vpsServer, /variationsWithVideo/, 'TikTok drafts must inspect configured videos from sibling variations');
assert.match(vpsServer, /Video indisponivel; rascunho seguira sem video/, 'An unavailable optional video must not block the draft');
assert.match(vpsServer, /video_uploaded: Boolean\(uploadedVideo\)/, 'Draft responses must report whether a video was uploaded');
assert.match(vpsServer, /Anuncio enviado sem video/, 'Draft responses must carry a non-blocking no-video notice');
assert.match(bulk, /Rascunho criado - enviado sem video/, 'The bulk result must inform when a draft was sent without video');
assert.match(bulk, /Enviado sem video/, 'Linked ads without video must keep an informational diagnostic');
assert.match(vpsServer, /WHERE parent_id = \? AND id <> \?/, 'TikTok drafts must find a sibling video within the same variation group');
assert.match(vpsServer, /buildTikTokDraftSkusVps/, 'TikTok drafts must build all SKUs for a variation group');
assert.match(vpsServer, /\[product, \.\.\.variations\]\.flatMap\(\(item\) => normalizeTikTokDraftImagesVps\(item\)\)/, 'A parent draft must reuse images from its variations');
assert.match(vpsServer, /\[product, \.\.\.variations\][\s\S]*?\.slice\(0, 9\)/, 'The TikTok parent gallery must fill from child images and respect the nine-photo maximum');
assert.match(vpsServer, /images, image_url FROM products[\s\S]*WHERE parent_id = \?/, 'Variation media must be loaded for the parent gallery fallback');
assert.match(vpsServer, /sales_attributes/, 'TikTok variation SKUs must include sales attributes');
assert.match(bulk, /Grupo de variacoes/, 'bulk screen must allow a parent product to create variation listings');
assert.match(bulk, /Produto pai/, 'bulk screen must visually identify selectable variation parents');
assert.match(bulk, /variacao\(oes\) \/ \{variationCount \+ 1\} SKU\(s\) serao enviados juntos/, 'bulk screen must explain that the group sends together and show the total SKU count');
assert.match(bulk, /buildTikTokBulkVariationGroups/, 'bulk screen must infer legacy parent groups by base name');
assert.match(bulk, /variationGroups\.parentIdByChild/, 'bulk screen must consolidate variation rows under their parent');
assert.match(bulk, /updateProductVariationGroup/, 'bulk screen must persist an inferred group before creating its TikTok draft');
assert.match(bulk, /groupChildren\.some/, 'bulk screen must show a parent when one of its variations matches the active filters');
assert.match(bulk, /getTikTokBulkGroupCategoryIds\(product, groupChildren\)/, 'bulk screen must inspect category mappings from the full variation group');
assert.match(bulk, /chooseTikTokBulkGroupCategoryMapping\(mappingResults\)/, 'bulk screen must reuse one unambiguous TikTok category mapping across the group');
assert.match(bulk, /Escolher categoria TikTok/, 'bulk rows must expose the TikTok category picker');
assert.match(bulk, /getCategories\(searchTerm\)/, 'the bulk category picker must search the live TikTok catalog');
assert.match(bulk, /localCategoryIds\.map\(\(localCategoryId\) => tiktokShopService\.saveCategoryMapping/, 'a parent category selection must be persisted for every local category represented by the group');
assert.match(bulk, /esta escolha vale para todo o grupo de variacoes/, 'the parent picker must explain the category scope');
assert.match(bulk, /Debug do envio em massa/, 'bulk failures must render a dedicated debug panel');
assert.match(bulk, /buildTikTokBulkDebug/, 'bulk failures must use the sanitized TikTok debug formatter');
assert.match(bulk, /registerBulkFailure\(action, product, error/, 'every bulk action failure must be registered per product');
assert.match(bulk, /Copiar debug/, 'bulk failures must expose a copy-debug action');
assert.match(bulk, /Ver detalhes tecnicos/, 'bulk failures must allow technical details to be inspected before copying');

console.log('TikTok Shop bulk screen static checks passed');
