import assert from 'node:assert/strict';
import fs from 'node:fs';

const server = fs.readFileSync('vps_server.js', 'utf8');
const serverCjs = fs.readFileSync('vps_server.cjs', 'utf8');
const service = fs.readFileSync('services/whatsappStatusCampaignService.ts', 'utf8');
const panel = fs.readFileSync('pages/admin/settings/marketing/WhatsAppStatusCampaignPanel.tsx', 'utf8');
const deployServerOnly = fs.readFileSync('deploy-vps-server-only.cjs', 'utf8');

for (const source of [server, serverCjs]) {
  assert.match(source, /CREATE TABLE IF NOT EXISTS whatsapp_status_campaigns/);
  assert.match(source, /CREATE TABLE IF NOT EXISTS whatsapp_status_campaign_logs/);
  assert.match(source, /MAX_WHATSAPP_STATUS_PRODUCTS_PER_RUN = 10/);
  assert.match(source, /\/message\/sendStatus\/\$\{encodeURIComponent\(instance\)\}/);
  assert.match(source, /WHATSAPP_STATUS_SEND_DEBUG/);
  assert.match(source, /slot_index/);
  assert.match(source, /product_ids JSON NULL/);
  assert.match(source, /parseWhatsAppStatusProductIds/);
  assert.match(source, /getWhatsAppStatusProductImage/);
  assert.match(source, /product\?\.image_url/);
  assert.match(source, /WHERE id IN \(\$\{placeholders\}\)/);
  assert.match(source, /groupWhatsAppStatusProductsByVariation/);
  assert.match(source, /Cores disponiveis/);
  assert.match(source, /specs, custom_fields/);
  assert.match(source, /sameWhatsAppStatusMemoryVariation/);
  assert.match(source, /runDueWhatsAppStatusCampaigns/);
  assert.match(source, /buildWhatsAppStatusProgress/);
  assert.match(source, /\/whatsapp\/status-campaigns\/progress/);
  assert.match(source, /ENUM\('sending','sent','failed','skipped'\)/);
  assert.match(source, /EVOLUTION_STATUS_TIMEOUT_MS/);
  assert.match(source, /EVOLUTION_STATUS_SERVER_URL/);
  assert.match(source, /EVOLUTION_INTERNAL_SERVER_URL/);
  assert.match(source, /EVOLUTION_STATUS_CONTACT_LIMIT/);
  assert.match(source, /EVOLUTION_STATUS_AUDIENCE_LIMIT/);
  assert.match(source, /selectWhatsAppStatusAudience/);
  assert.match(source, /hashWhatsAppStatusAudienceSeed/);
  assert.match(source, /EVOLUTION_STATUS_TIMEOUT_MS \|\| 90000/);
  assert.match(source, /isConfirmedWhatsAppStatusResponse/);
  assert.match(source, /status@broadcast/);
  assert.match(source, /O Status nao foi marcado como enviado/);
  assert.match(source, /const timedOut = error\?\.name === 'TimeoutError'/);
  assert.doesNotMatch(source, /status: timedOut \? 'sent' : 'failed'/);
  assert.doesNotMatch(source, /marcando como enviado para evitar repeticao/);
  assert.match(source, /markStaleWhatsAppStatusSendingLogs/);
  assert.match(source, /WHATSAPP_STATUS_STALE_SENDING_SECONDS/);
  assert.match(source, /envio ficou preso em andamento/);
  assert.match(source, /allContacts: false/);
  assert.match(source, /fetchWhatsAppStatusAudience/);
  assert.match(source, /\/chat\/findContacts\/\$\{encodeURIComponent\(instance\)\}/);
  assert.match(source, /statusJidList/);
  assert.match(source, /Contatos Status/);
  assert.match(source, /AbortSignal\.timeout\(timeoutMs\)/);
  assert.match(source, /VALUES \(\?, \?, \?, \?, 'sending', NULL, \?, \?\)/);
  assert.match(source, /CREATE TABLE IF NOT EXISTS whatsapp_status_campaign_trace_events/);
  assert.match(source, /appendWhatsAppStatusTrace/);
  assert.match(source, /sanitizeWhatsAppStatusTraceDetails/);
  assert.match(source, /safe\[key\] = sanitizeWhatsAppStatusDebugText/);
  assert.doesNotMatch(source, /safe\[key\] = sanitizeStatusDebugText/);
  assert.match(source, /audience\.request/);
  assert.match(source, /evolution\.request/);
  assert.match(source, /evolution\.response/);
  assert.match(source, /confirmation\.checked/);
  assert.match(source, /run\.completed/);
  assert.match(source, /\/whatsapp\/status-campaigns\/runs\/:runId\/trace/);
  assert.match(source, /trace_events/);
  assert.match(source, /UPDATE whatsapp_status_campaign_logs/);
  assert.match(source, /\/whatsapp\/status-campaigns\/:id\/send-now/);
  assert.match(source, /queued: true/);
  assert.match(source, /already_running/);
  assert.match(source, /setImmediate/);
  assert.match(source, /\/whatsapp\/status-campaigns\/run-due/);
  assert.match(source, /apikey\\s\*\[:=\]/);
  assert.doesNotMatch(source, /product\.images\.find\(\(value\) => String\(value \|\| ''\)\.trim\(\)\)/);
}

assert.match(service, /sendNow\(id: string\)/);
assert.match(service, /queued\?: boolean/);
assert.match(service, /already_running\?: boolean/);
assert.match(service, /WhatsAppStatusTraceEvent/);
assert.match(service, /trace_events: WhatsAppStatusTraceEvent\[\]/);
assert.match(service, /WhatsAppStatusCampaignProgress/);
assert.match(service, /progress\(\): Promise<WhatsAppStatusProgressResponse>/);
assert.match(service, /product_ids\?: string\[\] \| string \| null/);
assert.match(service, /\/whatsapp\/status-campaigns\/\$\{encodeURIComponent\(id\)\}\/send-now/);
assert.match(service, /daily_limit: Math\.max\(1, Math\.min\(10/);

assert.match(panel, /Status WhatsApp/);
assert.match(panel, /Enviar agora/);
assert.match(panel, /Copiar ultimo erro/);
assert.match(panel, /getCampaignCopyableDebug/);
assert.match(panel, /progress\?\.logs/);
assert.match(panel, /copyDebug\(copyableDebug\)/);
assert.match(panel, /max=\{10\}/);
assert.match(panel, /formatProductOptionLabel/);
assert.match(panel, /const selectableProducts = useMemo/);
assert.match(panel, /groupStatusProductsByVariation\(products\)/);
assert.match(panel, /selectableProducts\.map/);
assert.match(panel, /memoria_interna/);
assert.match(panel, /Preview do Status/);
assert.match(panel, /StatusPreviewCard/);
assert.match(panel, /Produto para adicionar/);
assert.match(panel, /selectedProductIds\.length >= 10/);
assert.match(panel, /getProductsByIds\(missingIds\)/);
assert.match(panel, /rows\.map\(normalizeProduct\)/);
assert.match(panel, /setSelectedProducts/);
assert.match(panel, /Adicionar produto/);
assert.match(panel, /ChevronLeft/);
assert.match(panel, /ChevronRight/);
assert.match(panel, /CampaignProgressBar/);
assert.match(panel, /Enviando agora/);
assert.match(panel, /Envio iniciado/);
assert.match(panel, /keepPolling/);
assert.match(panel, /Programado hoje/);
assert.match(panel, /Em envio/);
assert.match(panel, /Aguardando Evolution/);
assert.match(panel, /Tempo total/);
assert.match(panel, /Iniciados:/);
assert.match(panel, /Atualiza em/);
assert.match(panel, /Ver processo completo/);
assert.match(panel, /traceDetails/);
assert.match(panel, /event\.elapsed_ms/);
assert.match(panel, /loadProgress/);
assert.match(panel, /buildStatusCaption/);
assert.match(panel, /buildStatusPayload/);
assert.match(panel, /groupStatusProductsByVariation/);
assert.match(panel, /categories: \[form\.category_id\]/);

assert.match(deployServerOnly, /EVOLUTION_STATUS_SERVER_URL/);
assert.match(deployServerOnly, /EVOLUTION_STATUS_TIMEOUT_MS/);
assert.match(deployServerOnly, /EVOLUTION_STATUS_TIMEOUT_MS \|\| '90000'/);
assert.match(deployServerOnly, /WHATSAPP_STATUS_STALE_SENDING_SECONDS/);

console.log('whatsapp-status-campaign-vps-static.test.mjs: ok');
