import React from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, RefreshCw } from 'lucide-react';
import { shoppingListService } from '../../../services/shoppingListService';
import type { ShoppingListPurchase } from '../../../types/shopping-list';

const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0);
export default function ShoppingPurchasesPage() {
  const [purchases, setPurchases] = React.useState<ShoppingListPurchase[]>([]); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async () => { setLoading(true); try { setPurchases(await shoppingListService.listPurchases()); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  return <div className="space-y-6 animate-in fade-in"><div className="flex items-start justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><CheckCircle2 className="text-emerald-600" /> Compras efetuadas</h1><p className="mt-1 text-sm text-slate-500">Todos os itens já confirmados, em uma única tela.</p></div><div className="flex gap-2"><Link to="/admin/compras" className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Lista principal</Link><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-700 border border-slate-300"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /> Atualizar</button></div></div><div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Item</th><th className="px-5 py-3">Fornecedor/local</th><th className="px-5 py-3 text-right">Quantidade</th><th className="px-5 py-3 text-right">Preço pago</th><th className="px-5 py-3">Data</th><th className="px-5 py-3">Operador</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">Carregando…</td></tr> : purchases.length === 0 ? <tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">Nenhuma compra confirmada.</td></tr> : purchases.map((purchase) => <tr key={purchase.id}><td className="px-5 py-4 font-semibold">{purchase.item?.item_name}<p className="font-mono text-xs font-normal text-slate-500">{purchase.item?.sku || 'Sem SKU'}</p></td><td className="px-5 py-4">{purchase.supplier_name}<p className="text-xs text-slate-500">{purchase.purchase_location || 'Local não informado'}</p></td><td className="px-5 py-4 text-right">{purchase.quantity}</td><td className="px-5 py-4 text-right font-bold text-emerald-700">{money(purchase.unit_price)}</td><td className="px-5 py-4">{new Date(`${purchase.purchased_at}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className="px-5 py-4">{purchase.operator_name}</td></tr>)}</tbody></table></div></div>;
}
